### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by brandtabbott** [grid-js/gridjs#1000]
Looks like there hasn't been any recent releases and bug issues (one of which I'm running into) are auto closed by the bot 👎.  I'd really like to see this project continue 👍.  Please let us know the current state 😀.

**Comment by afshinm** [comment]
Hey @brandtabbott, yeah. sorry about that. The project is maintained and my intention is to keep the project up and running, I didn't have enough time recently to triage tickets though. I will hopefully fix some common issues today/tomorrow and release a new version.

Thanks for the heads up!
