### ISSUE TITLE
The POST Body:{} server request sends [object Object]

### ISSUE THREAD

**Issue by throwexceptions** [grid-js/gridjs#1040]
When I try to use the POST method and add parameters inside of the body:{}, It sends [object Object] instead of JSON format.

1. Create a load and import data from a remote URL. 
2. Use POST as method and Body : {} for your params.

Screenshot of Request to Server:

<img width="164" alt="Screen Shot 2022-06-27 at 1 28 54 PM" src="https://user-images.githubusercontent.com/17608701/175866221-0f7c87af-980b-41f8-9136-96f2ea597247.png">

Array Snippet:
`{
  server:
  body: {limit: 10}
  headers: {X-CSRF-TOKEN: 'tokentoken'}
  method: "POST"
  then:  ['id', 'name', 'email', 'action']
  total: 400
  url: "http://gridjs-research.test/user/fetch"
}`

**Comment by EnrickyHip** [comment]
Hello! I see you've closed this issue without any answer. Did you remember if you fixed it? if so, How? I'm getting this error and I need to know how to fix. Thanks.
