### ISSUE TITLE
Sortable function behaves unexpected in column with numbers

### ISSUE THREAD

**Issue by ben099** [grid-js/gridjs#1043]
I have a sortable table. In one column I list numbers (points) meant as a ranking. The sortable function sorts this column in a weird way.

**Unsorted (initial):**
290
238
218
174
143
113
89
14

**Sorted (by gridjs):**
113
14
143
174
218
238
290

**Expected:**
14
113
143
174
218
238
290

**Screenshot**
https://share.cleanshot.com/yq45bGivqjYTGoqhtriH

**Code for activating**
`$("#table-sortable").Grid({
search: true,
sort: true,
language: {
	'search': {
		'placeholder': 'Suche…'
	},
},
});`

**Comment by bguil** [comment]
Make sure that the values you use are numbers. In your example, values are sorted as strings (14 < 113 but "113" < "14").

**Comment by ben099** [comment]
Awesome, thank you so much for pointing me into the right direction.

**Comment by ben099** [comment]
It's awkward, but even when I convert from a string to an integer, it changes the behavior of the sorting.
Could you look again into this matter?

**Comment by bguil** [comment]
See screenshots below:
 * first screenshot: value are strings (with quotes), sorting is 1, 10, 2, 3
 * second screenshot: value are ints (no quotes), sorting is 1, 2, 3, 10

<img width="866" alt="Screenshot 2022-07-15 at 18 56 34" src="https://user-images.githubusercontent.com/687155/179272064-79ceda7f-d1dd-4629-8560-ad6d87475fd6.png">
<img width="866" alt="Screenshot 2022-07-15 at 18 57 08" src="https://user-images.githubusercontent.com/687155/179272091-109d9f77-818a-4965-ae1d-5d5a7de5dbbd.png">
