### ISSUE TITLE
How to Add Two button to one column

### ISSUE THREAD

**Issue by GoekhanDev** [grid-js/gridjs#1070]
Hello,

I'm trying to add two buttons to one column, the guide on the website only shows how to add one button per column, source https://gridjs.io/docs/examples/row-buttons/. I need one edit and delete button side by side in one column, I've tried to return two buttons but that just overrides the first button.

Kind Regards.

**Comment by gpiedimonte** [comment]
I think this is not an issue, move it to the discussion tab it's more appropriate

**Comment by bsoliveira** [comment]
try to pass to the formatter an array of buttons:

formatter: (cell) => [
      h('button1''),
      .h('button2'),
  ],

**Comment by GoekhanDev** [comment]
> try to pass to the formatter an array of buttons:
> 
> formatter: (cell) => [ h('button1''), h('button2'), ],

Thanks you very much, worked.
Closed.
