### ISSUE TITLE
Uncaught TypeError: grid.render is not a function

### ISSUE THREAD

**Issue by gpiedimonte** [grid-js/gridjs#1071]
**The bug**
render function is not present

**To Reproduce**
1. include this source:' <script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>
2. create a simple script ...
```
var grid = gridjs.Grid({
            className: {
                table: 'table table-striped',
            },
... etc
```
3.  at the end invoke the render function
`       
grid.render(document.getElementById('your-div-id-here')); 
`
4. you should get: Uncaught TypeError: grid.render is not a function

**Expected behavior**
it should appear a grid

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version [e.g. 5]

**Comment by ewwink** [comment]
it missing `new` keyword, it should be `var grid = new gridjs.Grid({})`

**Comment by gpiedimonte** [comment]
sorry..
