### ISSUE TITLE
Add ability to configure pagination result counts

### ISSUE THREAD

**Issue by gavinspr** [grid-js/gridjs#1119]
My team and I use gridjs for tables in our project and would like to be able to configure the pagination counts. With our tables we append a row of filters for users to sort the table with. If a set of filters are put in that return 0 results, the results section with still display 1 of 1. It would be helpful if would could easily change these results to display the value minus 1. 
![gridresults](https://user-images.githubusercontent.com/83553623/186204161-b47200d3-16ce-42cb-a49c-95e326963a11.png)

**Comment by Aloysb** [comment]
Hey @gavinspr if the filters is appended as a row, then the table is behaving as expected - since one row is displayed.

Adding a row to act as a filter is not really the intended use of the table.

Could you manipulate the text content of the pagination element to return the right number?
