### ISSUE TITLE
[Feature request] Extend cell formatter to header

### ISSUE THREAD

**Issue by sasha42** [grid-js/gridjs#112]
I am putting together a table which contains buttons in the header. Right now, there appears to be no clear way to add a button in the header `th` component. It is possible to add such a button into individual cells using the [formatter](https://gridjs.io/docs/examples/html-cells) function however.

It would be great if it would be possible to add custom html / cell formatting to the header of a table. Here is an example of how this could look like:
![image](https://user-images.githubusercontent.com/1775702/85959260-01fb7380-b950-11ea-9aca-b2ac848f18e4.png)

**Comment by afshinm** [comment]
Thanks @sasha42. I will release a version soon with `formatter` for columns.

**Comment by afshinm** [comment]
@sasha42 Added in 1.9.0! see https://gridjs.io/docs/examples/html-header-cells/
