### ISSUE TITLE
Dynamic Page Size Plugin Remove Itself on ForceRender

### ISSUE THREAD

**Issue by sathishk** [grid-js/gridjs#1125]
**Describe the bug**
We tried to add plugin that helps us to change the page limit based on user selection. Below is the Sample Code.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Grid JS | Pagination</title>
    <link
      href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div id="wrapper"></div>

    <script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>

    <script type="module" src="/js/grid-dynamic-page.js"></script>
  </body>
</html>
```

```
import { BaseComponent, Grid, h, PluginPosition } from "gridjs/dist/gridjs";

class DynamicPagePlugin extends BaseComponent {

    // Set Dynamic Page Size and Rerender
    setPageLimit(limit) {
        console.log('Set Page limit as ' + limit);
        this.config.instance.updateConfig({
        pagination: {
          enabled: true,
          limit: limit
        }
      })
        this.config.instance.forceRender();
    }

    render() {
        return h('span',{
            className:"text-xs text-gray-800 font-custom-font mr-1",
          },[
            "Show",
            h('select',{
                className:"text-xs text-gray-800 h-31 py-custom-7 pr-8 pl-2.5 rounded-4 border border-lightest-gray focus:outline-none focus:border focus:ring-sky-blue  focus:border-sky-blue focus:shadow-type1",
                
                onChange:(e)=>{
                    this.setPageLimit(e.target.value)
                }
            },[
                h('option',{value:2,selected: this.limit ==2 },"2"),
                h('option',{value:4, selected: this.limit ==4},"4"),
                h('option',{value:8,selected: this.limit ==8},"8"),
                h('option',{value:10, selected: this.limit ==10},"10") 
            ]),
            h('span',{
                className:"text-xs text-gray-800 font-custom-font ml-1",
              },"entries")
          ]);
        }
    
  }
    
  const grid = new Grid({
    columns: ['Name', 'Email', 'Phone Number'],
    data: [
      ['John', 'john@example.com', '(353) 01 222 3333'],
      ['Mark', 'mark@gmail.com',   '(01) 22 888 4444'],
      ['Sathish', 'john@example.com', '(353) 01 222 3333'],
      ['Thiru', 'john@example.com', '(353) 01 222 3333'],
      ['Saro', 'john@example.com', '(353) 01 222 3333'],
      ['James', 'john@example.com', '(353) 01 222 3333'],
      ['Manoj', 'john@example.com', '(353) 01 222 3333'],
      ['Thillai', 'john@example.com', '(353) 01 222 3333'],
      ['Sundar', 'john@example.com', '(353) 01 222 3333'],
    ],
    pagination: {
        enabled: true,
        limit: 2,
        summary: false
      }
  });
    
  grid.plugin.add({
    id: 'myDynamicPagePlugin',
    component: DynamicPagePlugin,
    position: PluginPosition.Header,
  });

  grid.render(document.getElementById('wrapper'))
  ```

**To Reproduce**
1. Open index.html in the browser.
2. Select Show Entries Select as 4

**Expected behavior**
Page Display 4 records.

**Actual behavior**
Page Display 4 records But the plugin dis appears.

**Screenshots**
![image](https://user-images.githubusercontent.com/1736813/186574939-6500a059-f38b-470c-9211-d34d8d233d4e.png)
![image](https://user-images.githubusercontent.com/1736813/186574978-1f8ac767-87ab-43e2-bcc6-4061c8de6a0e.png)

**Additional context**
In case if this is part oc customisation for existing plugin, Please provide the documentation.

**Comment by Robinyong** [comment]
you can try this

setPageLimit(limit) {
        this.config.instance.updateConfig({
            pagination: {
                enabled: true,
                limit: limit,
                server: {
                    url: (prev, page, limit) => `${prev}${prev.includes('?') ? '&' : '?'}limit=${limit}&offset=${page * limit}`
                },
                summary: true,
            },
        })

        var pluginsId = 0;
        for (let i = 0; i < this.config.instance.plugin.plugins.length; i++) {
            if (this.config.instance.plugin.plugins[i].component.name == 'DynamicPagePlugin ') {
                pluginsId = i;
            }
        }
        this.config.plugin.add({
            id: this.config.instance.plugin.plugins[pluginsId].id,
            component: this.config.instance.plugin.plugins[pluginsId].component,
            position: this.config.instance.plugin.plugins[pluginsId].position,
        });
        this.config.instance.forceRender();

        document.getElementById('ddlSelectGrid').value = limit;
    }

**Comment by Negwael** [comment]
I have the exact same issue creating a custom plugin for update pagination limit.
forceRender() do not render any custom plugins.

I tried few workaround as mentionned by @Robinyong but it never do the trick.

**Comment by somegooser** [comment]
I have the same issue.. forceRender removes all custom plugings... Force fetch data is enough for me but it does not exists unfortunately and forceRender breaks all custom plugings.

**Comment by Negwael** [comment]
forceRender() works with custom plugins since version 6. I guess issue can be closed.
