### ISSUE TITLE
Event Handling for Angular in ServerSide Rendering

### ISSUE THREAD

**Issue by alaksandarjesus** [grid-js/gridjs#1127]
I am trying to integrate gridjs with gridjs-angular and for server side rendering, i want to use service instead of server config object as in documentation. Why? So i could use the interceptor.

Is there a way i could capture the sort and search click.

**Comment by sk335577** [comment]
Hi, You can use javascript fetch interceptor.
`const { fetch: originalFetch } = window;

window.fetch = async (...args) => {
    let [resource, config ] = args;
    // request interceptor here
    const response = await originalFetch(resource, config);
    // response interceptor here
    return response;
};`
