### ISSUE TITLE
[Feature request] Button to add a record within the grid, similar to search input field

### ISSUE THREAD

**Issue by SwederSchellens** [grid-js/gridjs#113]
Currently, my button to add a record is 'floating' above or below the grid. I think it would be nice to have one as shown in this image:

![Grid_request_for_add_record](https://user-images.githubusercontent.com/13760419/85982994-53bc0080-ba19-11ea-8d93-bde78bc66d03.gif)

I would need to create my own dialog/page for the actual form and submit it to my server.

**Comment by afshinm** [comment]
Sure! will add that to the roadmap.

**Comment by afshinm** [comment]
@SwederSchellens just released 1.12.0 which adds plugins to Grid.js! https://gridjs.io/docs/plugin/basics

Thank you!

**Comment by shaheem-pp** [comment]
> @SwederSchellens just released 1.12.0 which adds plugins to Grid.js! https://gridjs.io/docs/plugin/basics
> 
> Thank you!






<img width="1440" alt="Screenshot 2022-11-14 at 10 38 18 AM" src="https://user-images.githubusercontent.com/46243023/201580118-69fd71ba-8695-4ebf-b712-9f7791b6f9cb.png">




shows page not found
