### ISSUE TITLE
Sorting fails if column data is an object with boolean fields

### ISSUE THREAD

**Issue by krootee** [grid-js/gridjs#117]
**Describe the bug**
Data for the table is returned via JSON from server-side and contains one of the columns with the following data:
"options: {
    viber: false,
    whatsapp: false
}"

Then this information is used in custom "formatter" to produce column text.
Rendering of the page works without issues, but enabling sorting ("sort: true") and then entering anything in the search box results in Console error
"[Grid.js] [ERROR]: TypeError: Cannot read property 'content' of undefined"

**To Reproduce**
Render the Grid with following data and enable sorting.

**Expected behavior**
Sorting works as expected ignoring such boolean fields.

**Comment by afshinm** [comment]
I will take a look @krootee

**Comment by afshinm** [comment]
@krootee i couldn't reproduce that error. Could you create a jsFiddle/CodeSandbox?
