### ISSUE TITLE
Bug on forceRender() method

### ISSUE THREAD

**Issue by VladRafli** [grid-js/gridjs#1217]
Hi, thanks for creating this great library. I found another bug in my project that so far I haven't found similar issues posted here.

**Describe the bug**
Rendering 2 instance of Grid in one page, when trying to force render with same config on this [issue](https://github.com/grid-js/gridjs/issues/1216). It returns error like this:

```
gridjs.module.js:22 [Grid.js] [ERROR]: The container element [object HTMLDivElement] is not empty. Make sure the container is empty and call render() again
```

**To Reproduce**
1. Initialize two Grid Js Instance, use same config as last [issue](https://github.com/grid-js/gridjs/issues/1216)
2. Run the page
3. See DevTools on console tab

**Expected behavior**
Re-fetch data from server, and re-render the grid

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)

**Additional context**

Current workaround to this issue maybe just reload the page and fetch the data again, if need to fetch different data with parameters, use method like query strings, etc.

**Comment by afshinm** [comment]
#1267 should fix this

**Comment by VladRafli** [comment]
> #1267 should fix this

Thank you so much for the new update, the update resolve this issue and tested on my local environment. Closing the issue...

**Comment by VladRafli** [comment]
As the update already published, and tried recreate the scenario with new version of this library. Seems the problem have been fixed.

Closing the issue, thank you.
