### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by simonpetry** [grid-js/gridjs#125]
**Describe the bug**
First off, thanks for making gridjs. Really impressed with how friendly the APIs are.
When working in react hot-reload environment, we're hit with an uncaught error when changes are made:

```javascript
Uncaught TypeError: Cannot read property 'filter' of undefined
```

Minified + beautified code reference:
```javascript
n.prototype.unregister = function(t) {
    if (t) {
        var e = this._steps.get(t.type);
        this._steps.set(t.type, e.filter((function(e) { <-------- this line, in `e.filter` `e` is `undefined`
            return e != t
        }
        ))),
        this.emit("updated", t)
    }
}
```

**To Reproduce**
https://codesandbox.io/s/awesome-rosalind-ku25j?file=/src/App.js
1. On the right is the preview, select "courses"
2. Look for `data` (line 38) and modify any of `title` values within it to something else, ex `Test4` -> `Test5` without saving it, just changing a character will trigger the error

**Comment by afshinm** [comment]
Thanks for reporting that error. I will patch that today in 1.10.
