### ISSUE TITLE
Open collective

### ISSUE THREAD

**Issue by sanch941** [grid-js/gridjs#1252]
I supposed to subscribe 50$ bronze sponsor recently, but subscribed to 2$ each month. Now i wanna change my subscription to bronze but i don't see any work, creator just bumps dependencies and that's all. Please give me hope that this project is not dead.

**Comment by afshinm** [comment]
I have been reading and monitoring issues but I didn't manage to reply to all of them. I have been working on a 6.0 version in this branch https://github.com/grid-js/gridjs/tree/functional, which converts the entire library to a functional component and should hopefully address many issues that have been mentioned by folks in the repo. Apologies for not replying to every single issue on GitHub, but I'm working on a better Grid.js. Stay tuned.
