### ISSUE TITLE
GET https://unpkg.com/preact@10.11.3/hooks?module net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by gk7279** [grid-js/gridjs#1281]
**Describe the bug**
GET https://unpkg.com/preact@10.11.3/hooks?module net::ERR_ABORTED 404

**To Reproduce**
1. 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" type="text/css"/>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" type="text/css"/>
<script src="https://unpkg.com/jquery/dist/jquery.min.js"></script>
<script src="https://unpkg.com/gridjs-jquery/dist/gridjs.production.min.js"></script>
import { Grid, html } from "https://unpkg.com/gridjs?module";

2. Inspect the html page.

**Expected behavior**
A table should've been presented.

**Desktop (please complete the following information):**
 - Browser : chrome

**Additional context
1. This file does not exist - https://unpkg.com/preact@^10.11.3/hooks?module
2. Instead, it needs to be replaced with - https://unpkg.com/preact@10.11.3/hooks/dist/hooks.js?module

**Comment by NetSpud** [comment]
Same problem here. Also occures in a different form when using it through
```js
new gridjs.Grid()
```

![image](https://user-images.githubusercontent.com/56541762/212753317-6df7099a-8ee7-4675-8cf6-4fb549d70011.png)

**Comment by afshinm** [comment]
I will have a look asap. Please revert to the previous version for now.

**Comment by afshinm** [comment]
@gk7279 @NetSpud Just pushed 6.0.3, could you test this version and let me know please?

**Comment by gk7279** [comment]
It works. Thanks.
