### ISSUE TITLE
new gridjs.Grid({ is not a constructor

### ISSUE THREAD

**Issue by cbessega2** [grid-js/gridjs#1282]
**Describe the bug**
Grid stop loading. It seems there was a change in the js library, and now the Grid object cannot be instantiated.

**To Reproduce**
Steps to reproduce the behaviour:
1. Import <script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>

2. Create a Grid with new gridjs.Grid({ ......})
4. Load the page
5. See js error

**Screenshots**
<img width="733" alt="Screenshot 2023-01-16 at 2 58 40 PM" src="https://user-images.githubusercontent.com/115636420/212758237-4d4834dd-2d37-4c85-93c2-056450a7b2b8.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 108.0.5359.124 (Official Build) (arm64)

**Additional context**
The tables were working until last night.

**Comment by GWustenstein** [comment]
Ditto, worked fine last night, reloaded today and the lib now fails, similar issues getting:
At first:
TypeError: loc is undefined   deep in a function called firstpartyFingerprintingListener(e)
at  if (loc.isFingerprinting) {

then later...
Uncaught TypeError: e is undefined
    <anonymous> store.ts:40
    <anonymous> gridjs.umd.js:1
    <anonymous> gridjs.umd.js:1
[store.ts:40:46](https://unpkg.com/gridjs/src/state/store.ts)
    <anonymous> store.ts:40
    <anonymous> gridjs.umd.js:1
    <anonymous> gridjs.umd.js:1

finally...
Uncaught TypeError: gridjs.Grid is not a constructor

**Comment by NetSpud** [comment]
Same problem. Related to #1281 I believe

**Comment by afshinm** [comment]
It seems like for some reason the Grid class is now accessible in `window.gridjs.Grid`. i.e the following should work:

```js
            new gridjs.Grid({
                sort: true,
                search: true,
                data: [
                  ['Mike', 33, 'mike@murphy.com'],
                  ['John', 82, 'john@conway.com'],
                  ['Sara', 26, 'sara@keegan.com']
                ],
                columns: ['Name', 'Age', 'Email']
              }).render(document.getElementById('wrapper'));
```

Working on a fix.

**Comment by cbessega2** [comment]
Thanks. @afshinm In the meantime, I reverted to a previous version (5.1.0) :-) 
Thanks for the great work.

**Comment by afshinm** [comment]
Update: It seems like the problem is with the bundler that we are using. I'm going to revert the bundler to the previous version and see if that fixes the issue.

**Comment by afshinm** [comment]
Found the issue, no need to revert. will publish 6.0.2 in a few mins. I apologies for any inconvenience caused!

**Comment by afshinm** [comment]
Just published 6.0.3, could you test this version and let me know if it works please @GWustenstein @cbessega2

**Comment by GWustenstein** [comment]
Just got the drop, works again... thanks for the speedy response!

**Comment by cbessega2** [comment]
All good @afshinm !! Thanks for the quick response!!

**Comment by afshinm** [comment]
Amazing! Thanks everyone

**Comment by somegooser** [comment]
Thanks for the quick responses!

I have another problem now:
It looks like gridjs BaseComponent is missing in the latest release. So extending plugins is not possible anymore.

**Comment by afshinm** [comment]
@somegooser Since Grid.js v6, all components are switched to Functional components, meaning you don't need to create/extend any base classes. I'm working on updating the Plugin docs and will release later today. For now, you can revert to v5 if you have any custom plugins.

**Comment by somegooser** [comment]
Oke thank you!

**Comment by GWustenstein** [comment]
Okay, I've noticed some wonkyness, will wait for the docs before submitting issues, for example search has now popped up where I have it disabled, etc.  It would be nice to version this stuff with the docs before rolling out to production, y'know...

In the prior versions I've had some pragmatic issues with how various features are enabled/disabled, for example on a column you can set hidden: true, but you can't hidden: false, you can sort: true, but you can't sort: false, you can set it's name, but you can't turn off it's header representation positively.  In order to have a js control have a clickbox enable/disable the header, one ends up having to set these function literals to foo: false (using a string literal or whatever) and hope grid does not barf from getting unrecognized parameters.

**Comment by GWustenstein** [comment]
BTW, the docs link at https://github.com/grid-js/gridjs is 404
I have the search box appearing, where before I would just have a selective search box appear by setting list_type=true (controlled by a gesture), now it appears all the time cluttering up the UI, even when set to false.
        search: {
          enabled: list_type,
          debounceTimeout: 500,
          server: {
            url: (prev, search) => {
              return updateUrl(prev, {search});
            },
          },
        },

**Comment by afshinm** [comment]
@GWustenstein You would need to remove the entire `search` property or set it to `undefined` to disable a plugin, e.g:

```
            newGrid({
                sort: true,
                search: undefined,
                data: [
                  ['Mike', 33, 'mike@murphy.com'],
                  ['John', 82, 'john@conway.com'],
                  ['Sara', 26, 'sara@keegan.com']
                ],
                columns: ['Name', 'Age', 'Email']
              }).render(document.getElementById('wrapper'));

```
