### ISSUE TITLE
'HTML in Cell' throws warning when table created from HTML table

### ISSUE THREAD

**Issue by zpottie** [grid-js/gridjs#1288]
**Describe the bug**
When using an HTML table as a datasource, the instructions to format HTML for a cell doesn't seem to work (fully). It seems to still render the HTML from the source table, but throws a warning in the console:
`[Grid.js] [WARN]: The data field for cell cb4a788e-a6c0-4e97-be97-4e520ca7a3a0 is not a primitive value. Did you mean to add a "formatter" function to this column?`

To be clear, the issue is more about the (redundant?) warning message in the console.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a gridjs table from an existing HTML table - ensure one of the cells/columns have HTML in it.
2. Load page in browser, open developer's console.
3. Warning should show in console.

**Expected behaviour**
Either, following the (formatter) instructions in the documentation should prevent the warning from appearing, or if no formatter is needed when the datasource is an existing table perhaps the documentation needs an update - which again, should lead to the warning message not being triggered.

**Screenshots**
Warning:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/9076608/213032297-f423dc08-75b5-4449-9ac1-0a3e30fa8911.png">

I tried both of the below and the results are the same:
<img width="245" alt="Screen Shot 2023-01-18 at 12 10 13" src="https://user-images.githubusercontent.com/9076608/213032871-78005946-e0f6-434e-bcf2-6c4186f4a4ee.png">
 
<img width="527" alt="image" src="https://user-images.githubusercontent.com/9076608/213032774-77d1df81-f762-4eea-8dff-533994feb85e.png">

**Desktop (please complete the following information):**
https://www.whatsmybrowser.org/b/WVZ1A

Let me know if you need anything else.

Thank you for this great JS table plugin! :D

**Comment by afshinm** [comment]
I'm going to release a new version in a few mins which removes that warning for now.

**Comment by afshinm** [comment]
https://github.com/grid-js/gridjs/releases/tag/6.0.5

**Comment by zpottie** [comment]
> I'm going to release a new version in a few mins which removes that warning for now.

I think such a warning is nice, just not in this context. Thanks for the quick response :)
