### ISSUE TITLE
ASAP gridjs shutdown on unpkg.com & cdnjs.com

### ISSUE THREAD

**Issue by puuble** [grid-js/gridjs#1290]
![image](https://user-images.githubusercontent.com/2932094/213185524-d62cc001-af55-4efa-869c-67d0f0b52284.png)
 <script src="https://unpkg.com/gridjs/plugins/selection/dist/selection.umd.js"></script>
Who is the push latest?

I am using this resource in my project which is close to 80. This resource is currently not working in order to make multiple selections. Please revert your last push commit.

 - stock all browser
 -Version 109.0.5414.87

**Comment by afshinm** [comment]
Make sure you are using the latest version of Grid.js. This issue is already solved. Here is a working example: https://codesandbox.io/s/gracious-elbakyan-6bxond?file=/index.html

**Comment by puuble** [comment]
> Make sure you are using the latest version of Grid.js. This issue is already solved. Here is a working example: https://codesandbox.io/s/gracious-elbakyan-6bxond?file=/index.html

Yes, I am sure I use the latest version. However, I found a hard copy on my computer. I solved it without CDN way.
