### ISSUE TITLE
[BUG] Ready and Load events are not being triggered

### ISSUE THREAD

**Issue by neto737** [grid-js/gridjs#1295]
**Describe the bug**
"Load" and "Ready" events are not working after update to v6.x

**To Reproduce**
1. Create a table with server-side data, pagination, sorting and search (I didn't test removing any of these plugins)
2. Render a table
3. Put a console log or whatever in a Grid.js event listener function
4. Nothing will happen, no logs on browser console

**Expected behavior**
Execute the code after the event trigger

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 109.0.5414.120
 - Probably non-browser specific and non device specific

**Comment by KillerDom1123** [comment]
Any idea how to work around this at all? This makes it all the more annoying to work around #1248 :frowning_face:

**Comment by neto737** [comment]
> Any idea how to work around this at all? This makes it all the more annoying to work around #1248 ☹️

I actually downgraded my GridJS to latest v5.x version, hope to update to latest version when this issue gets fixed

**Comment by KillerDom1123** [comment]
That's a shame. Any idea what the major changes from the current latest version to 5.x is please @neto737?

**Comment by rhyanmacedosilva** [comment]
Confirmed, I just reproduced the bug here, and also reverted to the latest release of version 5.
