### ISSUE TITLE
Selection plugin documentation mentions non-existing id function

### ISSUE THREAD

**Issue by cpba** [grid-js/gridjs#1297]
**Describe the bug**
From the [row selection example](https://gridjs.io/docs/plugins/selection/row-selection#example):

> You need to define an id function for your selection plugin. The id function must return a unique string for each row and is called to determine the identifier for each row.

However, it looks like the ability to add this function was removed in a recent version.

**To Reproduce**

1. Add `id` prop to selection plugins
2. Function is never called

**Expected behavior**

Expected `id` function to be called. Or documentation to describe the new procedure.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 109

**Additional context**
Looking into it, it looks like current versions automatically generate an id for each row, however, this id is different each time so it won't work with server-side pagination as it'll no longer point to the row once a new page is loaded.

What would be the current approach for storing and retrieving a custom row identifier?

**Comment by afshinm** [comment]
That's correct, the current version relies on the UUID that is generated at runtime. I just updated the docs. Thanks
