### ISSUE TITLE
Layout shift when dynamically hiding/showing columns

### ISSUE THREAD

**Issue by brunobely** [grid-js/gridjs#1304]
**Describe the bug**

I assigned 3 checkboxes each controlling the `hidden` property of a column. When dynamically changing the `hidden` property, sometimes (not every time) there is a layout shift. Tried on both Chrome and Firefox.

**To Reproduce**
1. Go to [this REPL](https://svelte.dev/repl/18e2ef880a7548e589ef9a0e3af7cf07?version=3.55.1)
2. Click on the checkboxes a few times and observe behavior

**Expected behavior**
I expect the table to stay exactly the same except for the column in question, which should appear or disappear. Instead it slightly moves around. There's a 2-step process going on (I can kinda see it in Chrome profiler's tiny screenshots but I'm not sure how to get a full-res version of those):

0. Change in `hidden` is triggered.
1. Table moves down slightly (~1-2px), the width for all shown columns changes slightly.
2. Table displays the expected state.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 109 and Firefox 109

**Comment by Zonalds** [comment]
Were you able to find a solution to this?
