### ISSUE TITLE
Create first-party Svelte component

### ISSUE THREAD

**Issue by Etzeitet** [grid-js/gridjs#1309]
**Is your feature request related to a problem? Please describe.**
I recently discovered GridJS and since I am using Svelte for a project, I naturally looked to see if there was a Svelte component for it. I was pleased when the docs pointed to such a component.

The component at https://github.com/iamyuu/gridjs-svelte is super simple and works well. However, I quickly discovered a bug which I created an issue for on iamyuu's repo. Unfortunately, it is then I noticed that iamyuu seems to have lost interest in the wrapper or just not had the time to maintain it. The latest release is over a year old, and the most recent activity was 10 months ago. I am always wary of using libraries/software that hasn't had attention for a while.

**Describe the solution you'd like**
My suggestion is that GridJS create a first-party Svelte component as you have done with Vue, React, and Angular.

**Describe alternatives you've considered**
I considered creating my own Svelte component, but I'd prefer one created by people who understand GridJS, Svelte, and JS/TS way better than I do.

**Additional context**
Nope.

**Comment by thelinuxlich** [comment]
Agree, they should remove the Svelte Integration from the docs, as the lib is completely broken
