### ISSUE TITLE
search placeholder not working

### ISSUE THREAD

**Issue by jhonoryza** [grid-js/gridjs#131]
![image](https://user-images.githubusercontent.com/5910636/86610775-040ca480-bfd8-11ea-82d1-f8782d71ee67.png)

here is my code:

search: {
            server: {
                url: (prev, keyword) => `${prev}?search=${keyword}`
            },
            placeholder: "Cari"
        },

**Comment by afshinm** [comment]
`placeholder` is actually moved to the `language` config, see https://gridjs.io/docs/examples/i18n

Apologies if it was confusing. I will update the docs.
