### ISSUE TITLE
Server side search being called two times when search keyword is present

### ISSUE THREAD

**Issue by mnsrulz** [grid-js/gridjs#1330]
**Describe the bug**
Server side search being called two times when search keyword is present and depending upon the race condition getting unexpected results.

**To Reproduce**
```
        const grid = new Grid({
            pagination: true,
            search: {
                keyword: 'back',
                server: {
                    url: (prev, keyword) => `${prev}?search=${keyword}`
                }
            },
            columns: ['Title', 'Director', 'Producer'],
            server: {
                url: 'https://swapi.dev/api/films/',
                then: data => data.results.map(movie => [movie.title, movie.director, movie.producer])
            }
        });
        grid.render(document.getElementById("wrapper"));
```
Open network tabs, you will two requests being issued to the server one with no search and the second with search keyword.
As you can see the first request data is rendered in the grid instead of the filtered result. It's sort of race condition too.

**Expected behavior**
Only one request should be made and appropriate data should be rendered in the grid.

**Screenshots**
![image](https://user-images.githubusercontent.com/1809086/223869425-8e837e40-0533-422a-aebf-5c6fd55c3d39.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave/Chrome
 - Version Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

**Comment by marcelloh** [comment]
When will this be merged?

**Comment by bruno-buiret** [comment]
Posting a message so that it won't be marked as stale/wontfix! =)

**Comment by bruno-buiret** [comment]
Still looking for this

**Comment by bruno-buiret** [comment]
Please don't mark this as stale :)

**Comment by afshinm** [comment]
A new version is now available. Please try v6.1.0 https://www.npmjs.com/package/gridjs
