### ISSUE TITLE
Svelte Repl broken

### ISSUE THREAD

**Issue by mmailaender** [grid-js/gridjs#1336]
**Describe the bug**

Opening the Svelte Repl from [this page](https://gridjs.io/docs/integrations/svelte) leads to the following bug:
![image](https://user-images.githubusercontent.com/87228994/226722607-8631cc66-d273-46ed-b942-804757bbe796.png)

**To Reproduce**
1. Go to https://gridjs.io/docs/integrations/svelte
2. Click on 'Try it out in the browser'
3. Wait
4. Error occurs

**Expected behavior**
Working demo

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 111.0.5563.65

**Comment by theodorejb** [comment]
The contents of `TotalSalaryPlugin.js` should be:
```js
import { PluginPosition, useSelector, useEffect, useState, h } from "gridjs";

function TotalSalaryPlugin() {
  const [total, setTotal] = useState(0);
  const data = useSelector((state) => state.data);

  useEffect(() => {
    if (!data) return;

    setTotal(data.toArray().reduce((prev, row) => prev + row[1], 0));
  }, [data]);

  return h(
    "div",
    {
      class: "total",
      style: {
        fontStyle: "italic",
        textAlign: "right",
      },
    },
    `Total: $${total.toLocaleString()}`
  );
}

export default {
  id: "salaryPlugin",
  component: TotalSalaryPlugin,
  position: PluginPosition.Footer,
};
```
