### ISSUE TITLE
tsc type checking fails in 6.0.6 but passes in 6.0.5

### ISSUE THREAD

**Issue by semmypurewal** [grid-js/gridjs#1344]
Thanks for such a great library! I'm fairly new to Typescript and grid.js, so this may be a problem on my end. But I thought I'd report it in case this is a problem for someone else.

I'm having trouble getting my `tsc` runs to pass with gridjs 6.0.6. I don't see this error with gridjs 6.0.5.

```
$ tsc --esModuleInterop --noImplicitReturns --noImplicitAny --allowImportingTsExtensions --jsx react --lib es2023,dom --noEmit ts/*.tsx
node_modules/gridjs/dist/index.d.ts:14:31 - error TS2307: Cannot find module 'src/i18n/language' or its corresponding type declarations.

14 import { useTranslator } from 'src/i18n/language';
                                 ~~~~~~~~~~~~~~~~~~~

Found 1 error in node_modules/gridjs/dist/index.d.ts:14
```

I'm importing gridjs in my `App.tsx` file like this:

```
import { Grid } from "gridjs";
```

and I'm using it in a functional React component as described in one of the examples:

```
  useEffect(() => {
    const grid = new Grid({
      from: tableRef.current,
      pagination: true,
      resizable: true,
      sort: true,
    }).render(wrapperRef.current);
  });
```

I'm able to fix the error by changing that line in `index.d.ts` to the following (note the dot slash in front of `src`):

```
import { useTranslator } from './src/i18n/language';
```

I'm pinning to gridjs 6.0.5 for now as a workaround.

**Comment by StephanTLavavej** [comment]
I'm also observing this issue with my first attempt to use gridjs in TypeScript.
