### ISSUE TITLE
The container element [object HTMLDivElement] is not empty. Make sure the container is empty and call render() again in react

### ISSUE THREAD

**Issue by suresh0318** [grid-js/gridjs#1345]
I'm using gridjs-react and I'm getting the following error.

[Grid.js] [ERROR]: The container element [object HTMLDivElement] is not empty. Make sure the container is empty and call render() again

Here is the code ..

import React from 'react'
import { Grid } from "gridjs-react";
import "gridjs/dist/theme/mermaid.css";

const Grid1 = () => {
  return (
    <Grid
  data={[
    ['John', 'john@example.com'],
    ['Mike', 'mike@gmail.com']
  ]}
  columns={['Name', 'Email']}
  search={true}
sort={true}
/>
  )
}

export default Grid1

**Comment by alaksandarjesus** [comment]
Clear the enter between opening and closing div.

**Working**

`<div class="grid languages"></div>`


**Not Working**


`<div class="grid languages">                  </div>`

**Comment by suresh0318** [comment]
Which div are you talking about?

**Comment by fpaz** [comment]
submitted a PR to fix this issue when using `gridjs-react` https://github.com/grid-js/gridjs-react/pull/414/commits/38e1544f9f2d0ef4dd6d28f4f13ea9d2b82b8354

**Comment by JuanM2020** [comment]
experiencing a similar issue when using gridjs-react with nextjs

**Comment by edwilliams** [comment]
This solved the issue for me:

```javascript
const Demo = ({ columns, data }) => {
  useEffect(() => {
    if (columns.length && data.length) {
      const container = document.getElementById('container')
      container.innerHTML = '' // empty container first
      const el = document.createElement('div')
      new Grid({ columns, data }).render(el)
      container.append(el) // then append grid to container
    }
  }, [columns, data])

  return <div id="container"></div>
}
```
