### ISSUE TITLE
JQuery - formatter causing grid to not load

### ISSUE THREAD

**Issue by adamcastle** [grid-js/gridjs#1354]
Please see the following
https://jsfiddle.net/adamcastle/h9Lzv3fo/
It is currently not loading.

If you remove the following line of code it will load correct. 
formatter: (cell) => html(`${cell}`)

**Comment by sirosfakhri** [comment]
Hi @adamcastle.
first sorry for my poor English.
well, I had the same problem and I fixed it with the below code.
of course I'm not using jQuery.

first you need to install with NPM.
`npm install gridjs --save`

then import like this:

```
import {html} from "gridjs";

window.html = html;
```

now just build your final script.

and finally 

``` 
columns: [
           'title',
            'slug',
            {
                 name:'action',
                  sort:false,
                  formatter: (tag) => html('<a href="${tag}">edit</a>'),
           }
        ],
```
