### ISSUE TITLE
ForceRender does not return "No records found" if data is empty

### ISSUE THREAD

**Issue by exiao** [grid-js/gridjs#1360]
**Describe the bug**
Use the search function to search for gibberish and see the table return just the header with no string message for an empty table.

If you forceRender a table with data as an empty list, you will also get this bug.

**To Reproduce**
1. Go to https://gridjs.io/docs/examples/force-render
2. Search for gibberish or anything that doesn't match the table
3. See the results with no NoRecordsFound error.

**Expected behavior**
No results found should appear

**Screenshots**
<img width="1146" alt="CleanShot 2023-06-09 at 16 29 09@2x" src="https://github.com/grid-js/gridjs/assets/2093036/08e26d9c-dcc4-471f-8c4d-59288b4ac20e">

**Code area which is not working**
https://github.com/grid-js/gridjs/blob/master/src/view/table/tbody.tsx

**Comment by hoangnt2** [comment]
Facing same error
