### ISSUE TITLE
Searching inside gridjs HTML fields

### ISSUE THREAD

**Issue by redskate** [grid-js/gridjs#1362]
Dear community,

first of all thanks so much for sharing such a nice tool like gridjs.

My table has nearly all columns filled with HTML links like

<a href="...">content</a>

How shoud I formulate the search function so that the normal gridjs search be executed also for those links considering only their content (and excluding the HTML stuff) ?

I tried to insert a search function like explained in the literarure but with no effort. Typing the keyword resulted in an empty result.

**Comment by dsentker** [comment]
You can create a custom search function like described here:
https://gridjs.io/docs/examples/search
