### ISSUE TITLE
Global events not triggering in UMD version

### ISSUE THREAD

**Issue by morelandjo** [grid-js/gridjs#1378]
**Describe the bug**
Global events such as ready and load do not appear to be firing.

**To Reproduce**
Add a ready function with a console log output, reload the page, no result in log

const thegrid = new gridjs.Grid({
  columns: [name: 'Test1,'Test2','Test3','Test4'],
  fixedHeader: true,
  height: '85vh',
  style: {
    th: {
      'font-size': '14px',
      'white-space': 'break-spaces'
    },
    td: {
      'font-size': '14px'
    }
  },
  data: [1,2,3,4]}).render(document.getElementById('wrapper'));
 
  thegrid.on('ready', () => console.log('test'));

 
**Expected behavior**
I would expect these events, such as load and ready to fire at the appropriate time

**Desktop (please complete the following information):**
Windows and Mac
Chrome, Firefox, Safari

**Comment by zpottie** [comment]
Appears to be related to #1349?
