### ISSUE TITLE
Element actions for triggering actions

### ISSUE THREAD

**Issue by nocodeventure** [grid-js/gridjs#143]
We're looking for an option to add element actions to trigger certain actions like deleting a row. Checkboxes would be great too but I saw that was already requested.

Great work so far

**Comment by afshinm** [comment]
@nocodeventure do you want to add buttons to each cell? have you seen this example https://gridjs.io/docs/examples/react-cells

**Comment by nocodeventure** [comment]
Ah thanks so much, would this also allow us to add icons?

**Comment by afshinm** [comment]
@nocodeventure yes! you can also add icons using the React wrapper. I have recently added a React component wrapper to gridjs-react.
