### ISSUE TITLE
[Sorting] Back to Normal State for Third Press

### ISSUE THREAD

**Issue by amatzen** [grid-js/gridjs#144]
Currently the Sorting System is:
![Image of current sorting](https://screenshots.amatzen.dk/Y4me39dK50K2TuCKB8.gif)

The first state is meant by:
![Image of first state](https://screenshots.amatzen.dk/yO1TrhW2W2VB7IMLoN.png)

But you can never return to the first state by clicking the sorting buttons, after you've just used them once. I think that it hurts the user experience, and I would like the sorting to go back to the first state, when a sorted column has been pressed third time.

Thank you in advance! And keep up the amazing open source project!

**Comment by afshinm** [comment]
@amatzen you can remove the sort from a column by **holding the shift key** and clicking on the sort buttons. You can also sort multiple columns by holding the shift key and clicking on multiple columns.

Let me know this is confusing. I'm happy to improve it.

**Comment by amatzen** [comment]
Oh nice! But I still think it should be the third press, that removes the sort, since most websites already uses this. Mostly for the UX for the common user.

**Comment by afshinm** [comment]
@amatzen I see. yeah I guess I can add an option to enable that behavior, too. Thanks for the suggestion!
