### ISSUE TITLE
Support for accessing nested data

### ISSUE THREAD

**Issue by dgaus** [grid-js/gridjs#154]
HI. I am loading data from JSON and have some nested fields I would like to access. The use case is I have some dynamic columns. IE

```
[ { id: 1, name: "foo", extra_info: { version: "2.0" } } ]
```
Using dot or bracket notation in the `id` field seems to have no effect (`id: "extra_info.version"` or `id: "extra_info['version']"` I can get the value to display by using a custom formatter, but then sorting does not work. It would be nice to be able to access these fields using dot notation on the ID. Let me know if I can clarify or help with anything, thanks.

**Comment by afshinm** [comment]
@dgaus my understanding is that you can either pre-process your JSON and flatten the properties or use the `formatter` callback to select your data. Do you think you can potentially use one of those solutions?

Also, I'd like to see how you initiated your Grid.js instance. It would be great if you create a Codesandbox or paste your code here.

**Comment by dgaus** [comment]
Flattening the properties is what I'm doing now, but it could potentially lead to name clashes and adds one extra step. The formatter is the first thing I tried, but as I mentioned sorting doesn't work that way. I was using vue-gridjs and the initialization was pretty standard, with data fetched externally. I don't have the code as it was just an experiment using gridjs, but basically what I would like to do is

```
new Grid({
  columns: [{
    id: "name"
    name: "Name",
  }, {
    id: "extra_info.version"
    name: "Version",
  }]
})
```

keeping in mind the fields in `extra_info` are not static so I have a variable number of extra columns that are dynamically rendered depending on the json data.

**Comment by afshinm** [comment]
@dgaus gotcha, that makes sense. I will release another version in a few days which will add a selector function to columns.

**Comment by afshinm** [comment]
@dgaus added in 1.14.0.
