### ISSUE TITLE
Search Customization

### ISSUE THREAD

**Issue by Zegoverno** [grid-js/gridjs#157]
**Is your feature request related to a problem? Please describe.**
I have a cell where the value is an array of categories and I can't search a specific category inside this array

**Describe the solution you'd like**
would like to be able to customize the search engine to adapt to this scenario. Something like this, I get the Search Input, and if the cell is an array or another structure (dictionary), search for value inside it.

**Comment by cedriking** [comment]
I was wondering if this is possible too. I would like to be able to do a search by userID and username, but the userID I don't want it to be visible.

**Comment by afshinm** [comment]
yeah that makes sense. I will release a new version soon with that feature! thanks

**Comment by afshinm** [comment]
@cedriking @Zegoverno please install 1.13.0 and use the `selector` config in your search config to customize the global search: https://github.com/grid-js/gridjs/blob/master/src/view/plugin/search/search.tsx#L15
