### ISSUE TITLE
Adding useQuery option the server feature

### ISSUE THREAD

**Issue by Zegoverno** [grid-js/gridjs#158]
**Is your feature request related to a problem? Please describe.**
Today you can pass the URL and some parameters to the server and it uses fetch to get the data from the server-side.
I have a useQuery connected to firebase, would be nice to pass this instead of a URL.

**Describe the solution you'd like**
Receive the useQuery, verify the current state (loading, error, success) and return the data

**Describe alternatives you've considered**
I treat the useQuery and after I got success I render the Grid Component with the data. (lose the loading feature in this case)

**Additional context**
Also, would be nice if the logic to getMore for pagination purpose was handled by the server.

**Comment by afshinm** [comment]
makes sense. added to the backlog.
