### ISSUE TITLE
What if we could create a more powerful html creator function

### ISSUE THREAD

**Issue by well-ington** [grid-js/gridjs#179]
I'm using GridJS on my current project and something that was bothering me is that I was unable to pass a scoped function to the `html` creator, from `src/util/html.ts`. I needed to get Preact as a dependency and return an VNode to solve my problem (the problem was to call a scoped function with scoped values in an event).

It could be fixed by updating the code:
Export the VNode creator imported from `Preact` inside `html.ts` file or we could create a new function (or improve an existing one) to pass scoped args to the created VNode html element.

Or it could be fixed by updating the docs, creating an example using Preact to pass scoped function to cells.

I would gladly open a PR regarding this issue 😁

**Comment by afshinm** [comment]
@well-ington We have some examples on this page https://gridjs.io/docs/examples/virtual-dom but I guess you're right and it makes sense to add some tips to other examples and mention that Preact's VNode can be used directly as well.
