### ISSUE TITLE
Configure style & zebra stripe ?

### ISSUE THREAD

**Issue by Fxztam** [grid-js/gridjs#184]
Is there a way to configure the grid style: fonts, colors of header & rows .. and `zebra stripes`: {true | false} ?

**Comment by afshinm** [comment]
@Fxztam yes, have you tried https://gridjs.io/docs/examples/css-style or https://gridjs.io/docs/examples/css-in-js?

**Comment by Fxztam** [comment]
That's exactly what I was looking for!
Great, I like it.

**Comment by Olliebrown** [comment]
I'm still wondering how one achieves zebra-stripes for the rows.  'styles' does not expose an object for a row (tr) and a more complex CSS selector like tr:nth-child(even) doesn't seem possible with what is available here.  Classname also does not offer a way to distinguish every other row (or any rows) that I can see and I don't want to delve into css-in-js (nor do I see how it would solve this problem).

I even tried putting a general tr:nth-child(even) rule in a global style tag but it didn't seem to get picked up (although the environment is kinda weird that I'm in).

I gotta be missing something!

**Comment by xididri** [comment]
Here is how I do it with [react-jss](https://cssinjs.org/react-jss/):


```js
const useStyles = createUseStyles({
	table: {
		// alternating row colors
		'& tr:nth-child(odd)': { backgroundColor: 'white' },
		'& tr:nth-child(even)': { backgroundColor: 'gray' },
	},

	td: {
		backgroundColor: 'transparent !important', // override td.gridjs-td
	},

});
```

```js
const classes = useStyles();
```


```jsx
<Grid
  data={tableData}
  className={{
    table: classes.table,
    td: classes.td,
  }}
/>

**Comment by pauldmps** [comment]
Can this be implemented using SCSS modules? I tried setting both className and style but but both doesn't work.

**Comment by jwmurray** [comment]
@Olliebrown ,

This question solves our problem: https://stackoverflow.com/questions/75501116/how-to-create-different-background-for-my-table-row-nth-child

While you cannot affect the background of TR directly, you can select the TD's of the Even TR's and then apply the color to those TD's as shown in this SO question.
