### ISSUE TITLE
Multi-line for cells

### ISSUE THREAD

**Issue by sabatale** [grid-js/gridjs#185]
**Describe the bug**

Not really a bug since I assume this is by design.

For a cell with a long text (such as a Title or a short description), it looks like the line goes on forever.

This forces the table to enable horizontal scrolling, which is not always nice.

**Expected behavior**

What is the recommended approach right now?

Is it to apply HTML formatting somehow? Or are they standard cases where the multi-line applies automatically?

Or simply applying a character limit based on the width? (e.g. "ABCDEF" to "ABC...")

Thanks again for your project!

**Comment by afshinm** [comment]
@sabatale have you tried disabling the `autoWidth` option (https://gridjs.io/docs/config/autoWidth) and set the width for each column manually?
