### ISSUE TITLE
Release 1.15.0 is broken for server side data loading

### ISSUE THREAD

**Issue by krootee** [grid-js/gridjs#190]
**Describe the bug**
Server-side data loading is broken with 1.15 - downgrading to release 1.14 fixes the issue.
Gridjs breaks at processing data from URL with exception
"[Grid.js] [ERROR]: TypeError: data.data is undefined log.ts:17:14
    error log.ts:17
    process pipeline.ts:208
    a tslib.es6.js:100
    a tslib.es6.js:81
    a tslib.es6.js:72"

**To Reproduce**
create gridjs with server-side data loading 
            server: {
                url: '/comment/all',
                then: data => data.data.map(entry => [entry.date, entry.numbers, entry.comment])
            },
URL /comment/all return sample data
{"data":[{"comment":"test1","date":"2020-08-02","numbers":[123]}],"has_more":false,"object":"list","total_cards":1}

**Expected behavior**
Data loading fro URL works.

**Comment by afshinm** [comment]
I will take a look asap

**Comment by afshinm** [comment]
Found the issue, I will release another patch in a few mins. Apologies.

**Comment by afshinm** [comment]
@krootee could you please install 1.15.1 and confirm if it's fixed for you?

**Comment by krootee** [comment]
@afshinm Tested 1.15.1 and its working now.

Thank you!
