### ISSUE TITLE
Does gridjs support angular 9 or 8?Is there any examples?

### ISSUE THREAD

**Issue by wcc526** [grid-js/gridjs#193]
Does gridjs support angular 9 or 8?Is there any examples?

**Comment by afshinm** [comment]
We don't have any wrappers for Angular yet but there are some open projects (e.g. https://github.com/salamaashoush/gridjs-angular) working on this integration. I will add more details to gridjs.io soon.

**Comment by salamaashoush** [comment]
@wcc526I I published it on npm you can try it now https://www.npmjs.com/package/gridjs-angular
