### ISSUE TITLE
Installing via "npm i" doesn't appear to work at the moment. 

### ISSUE THREAD

**Issue by joekrump** [grid-js/gridjs#2]
Running `npm i gridjs` seems to install a different package than this one so unfortunately I'm unable to play around with this at the moment.

This is what appears to get installed instead: https://github.com/mafintosh/gridjs It seems like there may be some sort of naming collision on `npm`.

**Comment by afshinm** [comment]
That definitely seems like an npm issue @joekrump. Can you reproduce it using Codesandbox?

**Comment by afshinm** [comment]
@joekrump take a look at this https://codesandbox.io/s/cold-frost-ft5vp -- looks like it managed to resolve the dependencies correctly.

**Comment by joekrump** [comment]
Nice! Yes, looks like it resolves correctly on codesandbox. On stackblitz it does not 😢 https://stackblitz.com/

**Comment by afshinm** [comment]
Ah I see. Let me create a sanbox on Stackblitz, too. 

Out of curiosity, how did you find out about this project @joekrump? :)

**Comment by afshinm** [comment]
btw, I managed to create an app on Stackblitz: https://stackblitz.com/edit/js-oksqvh

**Comment by joekrump** [comment]
@afshinm I came across the project as I was in between things and had just heard about https://js.coach/ so I checked it out and saw this project at the top of the list and it tweaked my interest as I'm alway interested in framework agnostic libraries for building UI.

<img width="1395" alt="screenshot" src="https://user-images.githubusercontent.com/3317231/83200214-b313b180-a0f7-11ea-9c1a-3a45571b7871.png">

**Comment by afshinm** [comment]
Cool! thanks @joekrump.
