### ISSUE TITLE
Provide a way to identify cells in a particular "column" with a custom class or data identifier.

### ISSUE THREAD

**Issue by cdvillard** [grid-js/gridjs#213]
**Is your feature request related to a problem? Please describe.**
Tables, for all their potential, are woefully underserved when it comes to responsive design. I'm using Grid.js to build a web application in Vue, and decided to hack together a responsive style turning the rows into a sort of list of cards. I'd like to make these styles reusable across the different kinds of tables we have, but a challenge is that the data isn't always the same. I could go so far as to try and mandate certain restrictions on how tables are built (ie: dates always in the first column), but I feel that would be removing flexibility.

**Describe the solution you'd like**
A better solution would be to be able to declare either a class name or data attribute when declaring columns that would be shared with all the cells of that "column", in a similar fashion to how we can already declare a name or id. In that way, a designer can have a more accessible way to design a uniform solution for responsive designs. For example, if I'd like to able to declare that `tr`s in a media query should use `display: flex`, I can set the `order` of all cells to `100` and then set the order of `.dateCreated` or `[data-date] to `0`.

**Describe alternatives you've considered**
Perhaps a simpler solution could be to use the name property that's already being declared on the columns and attaching that as a data attribute to the individual cells. You're essentially accomplishing the same thing without the added overhead of transforming new properties.

**Comment by lesaff** [comment]
@cdvillard I agree. I ran into the same issue with not being able to easily add class name(s) to a particular column. For now, this is my solution:

To access the third TD cell from the left:

```
td.gridjs-td:nth-of-type(2) {
    text-align: right;
}
```

**Comment by cdvillard** [comment]
I can definitely work with that, but I need to.be able to do this on a component per component basis, and after a while, that doesn't scale too well.

**Comment by afshinm** [comment]
Makes sense. I will try to add className for columns and/or `data-*` attribute for the `td`s. Thanks for the suggestion @cdvillard

**Comment by afshinm** [comment]
@cdvillard @lesaff added in 1.16.0 https://github.com/grid-js/gridjs/releases/tag/1.16.0.

**Comment by michaelschofield** [comment]
@afshinm Hot damn dude. I just want to appreciate you out loud for how well you maintain this project.

**Comment by afshinm** [comment]
No worries @michaelschofield :)
