### ISSUE TITLE
Add Checkbox with mark all options to first column?

### ISSUE THREAD

**Issue by qant** [grid-js/gridjs#230]
Hi there! Is it possible to get first column as checkbox?

Can you guide with simple example how i can do this?

I understand it may be possible to modify html structure after whole table is rendered... but i wold like to make some changes in .ts files to add this as feature. 

Just let me know where with some small example may be its not so hard to implement.

Thank you!

**Comment by afshinm** [comment]
@qant sure, I'm happy to add an example for that.

**Comment by afshinm** [comment]
The selection module has been introduced in v3: https://gridjs.io/docs/examples/selection

**Comment by usyeimar** [comment]
![imagen](https://user-images.githubusercontent.com/71295346/177387222-505a7df1-c521-4484-96a6-7b13b89a8272.png)
Hello, this page is not found in the documentation
