### ISSUE TITLE
The column grid does not re-size correctly

### ISSUE THREAD

**Issue by gustavoaalves** [grid-js/gridjs#236]
**Describe the bug**
The column grid does not re-size correctly according column value size when we are using pagination.

**To Reproduce**
1. Generate a grid with pagination wiht limit equal 2 where the first and second records has the first column value with only 5 characters and the third record has the first column value with 20 characters.
2. Click on page 2
3. See error

**Expected behavior**
Resize of first column according the size of these column values.

**Screenshots**

![image](https://user-images.githubusercontent.com/11478696/91878676-0563f180-ec56-11ea-82f4-87ef89ceb881.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version Version 84.0.4147.125 

**Additional context**

**Comment by afshinm** [comment]
@gustavoaalves thanks for opening this ticket. I can see how that bug can occur. Grid.js takes the first few rows and calculates the width of each cell and uses the same width for all columns. This approach has some pros and cons but overall, it covers a lot of cases correctly. 

What I can do is:

 - Exposing the adjustHeader API so that you can manually call it and Grid.js adjusts the header for you
 - Setting some CSS rules to break words if they are wider than their container

**Comment by dmullis** [comment]
I am hitting the same or related bug.  Differences from the example above:
  1. pagination disabled
  2. long text fields are reflowing at word breaks, so last few characters are clipped off

For my application this is a blocker.  Currently trying to hack around it in various ways.

**Comment by systemcrash** [comment]
Recommend word breaks for all cell content, i.e. whole table. Resizing page mashes column text into each other. Setting the HTML table tag `style` value to `word-break: break-word` gives the desired result. e.g. in the js:
```javascript
  grid = new gridjs.Grid({
  sort: true,
  search: true,
...
  style: {
    table: {
      'text-align': 'right',
      'word-break': 'break-word'
    }
  }
...
```

**Comment by afshinm** [comment]
I believe this issue has been fixed. Please let me know if anyone has this issue.

**Comment by banshiAnton** [comment]
Hi @afshinm i have faced with this issue

page 1
![1](https://user-images.githubusercontent.com/20343723/115425933-bb417780-a208-11eb-8255-8a72971f06d9.png)
and when i go to page 2
![2](https://user-images.githubusercontent.com/20343723/115425950-c0062b80-a208-11eb-89b6-64ddbe653e53.png)

so i think we need to recalculate column widths after each pagination page changes
i forked you lib and add some changes
https://github.com/banshiAnton/gridjs/commit/4d142cf9d580b65ac3bf58fd6a3c89a53ec3067f
it helped me, but i think you can find more pretty solution

**Comment by afshinm** [comment]
@banshiAnton interesting. Grid.js calculates the widths only once and only for the first page. It assumes you have more or less the same data for the next pages as well. I can see that we having an option to calculate the width after each page could be useful and can fix your issue as well. 

Could you open another GitHub issue and mention the details of this feature (+ screenshots)? I'm happy to work on it.

**Comment by banshiAnton** [comment]
Of course, thank for quick reply
