### ISSUE TITLE
Example not working: The container element [object HTMLDivElement] is not empty

### ISSUE THREAD

**Issue by kartikye** [grid-js/gridjs#237]
**Describe the bug**
The example code does not run.

**To Reproduce**

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" />
    <script src="https://unpkg.com/gridjs/dist/gridjs.production.min.js"></script>    
</head>

<body>
    <div id="wrapper">
    </div>

    <script>
        new gridjs.Grid({
          columns: ["Name", "Email", "Phone Number"],
          data: [
            ["John", "john@example.com", "(353) 01 222 3333"],
            ["Mark", "mark@gmail.com", "(01) 22 888 4444"],
            ["Eoin", "eoin@gmail.com", "0097 22 654 00033"],
            ["Sarah", "sarahcdd@gmail.com", "+322 876 1233"],
            ["Afshin", "afshin@mail.com", "(353) 22 87 8356"]
          ]
        }).render(document.getElementById("wrapper"));
    </script>
</body>

</html>
```

**Expected behavior**
Error in console:
[Grid.js] [ERROR]: The container element [object HTMLDivElement] is not empty. Make sure the container is empty and call render() again

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by radiospiel** [comment]
You must remove all space in the wrapper div definition; i.e. it must read `<div id="wrapper"></div>`, no newline etc.

**Comment by afshinm** [comment]
I believe what @radiospiel suggested is correct.

**Comment by lukas-santiago** [comment]
How can I handle this situation in React?

I have two components, one with _gridjs_ and another one with _gridjs-react_. These two components keeps throwing this error.

This is the code:
`
import React, { useEffect, useRef, useState } from "react";
import { Grid } from "gridjs";
import { Grid as GridComponent } from "gridjs-react";

import "gridjs/dist/theme/mermaid.css";


export function MyComponent(props) {
    const row = () => ["faker.name.findName()", "faker.internet.email()"];
    const [data, setData] = useState([row()]);
    const update = () => {
        setData(data.slice(0).concat([row()]));
    }

    return (
        <div>
            <button onClick={update.bind(this)} className={"py-2 mb-4 px-4 border rounded-md text-white bg-blue-600"}>
                Add record
            </button>
            <GridComponent
                data={data}
                columns={['Name', 'Email']}
                pagination={{
                    limit: 5,
                }}
            />
        </div>
    );
}

export function HelloWorld() {
    const wrapperRef = useRef(null);

    const grid = new Grid({
        columns: ['Name', 'Email', 'Phone Number'],
        data: [
            ['John', 'john@example.com', '(353) 01 222 3333'],
            ['Mark', 'mark@gmail.com', '(01) 22 888 4444']
        ]
    });

    useEffect(() => {
        setTimeout(() => grid.render(wrapperRef.current), 5000)
    });

    return (<div ref={wrapperRef} />);
}
`

**Comment by suresh0318** [comment]
> How can I handle this situation in React?
> 
> I have two components, one with _gridjs_ and another one with _gridjs-react_. These two components keeps throwing this error.
> 
> This is the code:
> 
> ```
> import React, { useEffect, useRef, useState } from "react";
> import { Grid } from "gridjs";
> import { Grid as GridComponent } from "gridjs-react";
> 
> import "gridjs/dist/theme/mermaid.css";
> 
> export function MyComponent(props) {
>     const row = () => ["faker.name.findName()", "faker.internet.email()"];
>     const [data, setData] = useState([row()]);
>     const update = () => {
>         setData(data.slice(0).concat([row()]));
>     }
> 
>     return (
>         <div>
>             <button onClick={update.bind(this)} className={"py-2 mb-4 px-4 border rounded-md text-white bg-blue-600"}>
>                 Add record
>             </button>
>             <GridComponent
>                 data={data}
>                 columns={['Name', 'Email']}
>                 pagination={{
>                     limit: 5,
>                 }}
>             />
>         </div>
>     );
> }
> 
> export function HelloWorld() {
>     const wrapperRef = useRef(null);
> 
>     const grid = new Grid({
>         columns: ['Name', 'Email', 'Phone Number'],
>         data: [
>             ['John', 'john@example.com', '(353) 01 222 3333'],
>             ['Mark', 'mark@gmail.com', '(01) 22 888 4444']
>         ]
>     });
> 
>     useEffect(() => {
>         setTimeout(() => grid.render(wrapperRef.current), 5000)
>     });
> 
>     return (<div ref={wrapperRef} />);
> }
> ```



> 

Have you got the solution?
