### ISSUE TITLE
Share formatter callback with all columns

### ISSUE THREAD

**Issue by thewebartisan7** [grid-js/gridjs#245]
**Is your feature request related to a problem? Please describe.**

I have an html table with several cell that has HTML, and multiple columns can be in different cells.
Right now with formatter() method seem that I can only format single column.

**Describe the solution you'd like**

I would like to be able to have single template like below semplified example using JSRender:

```html
              <script id="tableTamplate" type="text/x-jsrender">
                    <table id="myTable" class="table">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Created</th>
                            <td>Actions</td>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td class="custom-class">{{:id}}</td>
                            <td>
                                  <strong>{{:name}}</strong>
                                  {{:username}} {{:role}}
                             </td>
                            <td class="another-class"><a href="mailto:{{:email}}">{{:email}}</a></td>
                            <td>{{:created_at}}</td>
                            <td><a href="{{:url_edit}}">Edit</a></td>
                        </tr>
                        </tbody>
                    </table>
```

Next I want create one single JS code that initialize my tables, where I pass variable via data attribute like URL, table template and other variable things.

```js
            // Semplified version

            const el = document.querySelectorAll('[data-mygrid]');
            let gridElement = el.getAttribute('data-mygrid');
            let gridUrl = el.getAttribute('data-mygrid-url');
            let gridColumns = JSON.parse(el.getAttribute('data-mygrid-columns'));
            let templateId = el.getAttribute('data-mygrid-template');

            const myGrid = new Grid({
                columns: gridColumns,
                server: {
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: gridUrl,
                    then: data => data.data,
                    total: data => data.meta.total
                },
               // here add formatter() for all columns using template templateId
            });
            myGrid.render(document.getElementById(gridElement));
```

And last part thing below html that can be defined for each table:

```html
<div
     id="gridUsers"
     data-mygrid="gridUsers"
     data-mygrid-url="/users"
     data-mygrid-columns='{{ json_encode(["id" => "ID", "url" => "URL", "name" => "Name", "email" => "Email", "username" => "Username", "created" => "Created", "updated" => "Updated"]) }}'></div>
```

Note that I am passing columns with key and value, where key is from JSON and value is title in header. Here is a working example where I define for each column separate template: https://gist.github.com/thewebartisan7/9bb0fa102b6337569b8879e2809e93d9 

**Additional context**

Above is just a semplified version of table, but I have more complex html table see below screenshot, with checkbox for select many rows, details of a record with additional ro , so that in my case I will have two tr for each entry, example below in screenshot. I can't even define custom class for single cell (TD) right now, but only the same class for all, because I also use responsive classes for each cell to show/hide depending on screen size. Using single template I can define also different class for each cell and add complex html.

I hope that I explain well my usecase, please let me know if you need more info.

Thanks!

<img width="618" alt="Screenshot 2020-09-09 at 04 29 59" src="https://user-images.githubusercontent.com/57477934/92547647-a1dd5380-f255-11ea-9195-3e8567b503ed.png">

<img width="1163" alt="Screenshot 2020-09-09 at 04 23 07" src="https://user-images.githubusercontent.com/57477934/92547626-9427ce00-f255-11ea-8323-dc16d8888b93.png">

**Comment by afshinm** [comment]
thanks @thewebartisan7. Have you tried cell attributes: https://gridjs.io/docs/examples/cell-attributes/? With that function, you can define attributes for each cell (e.g. a className).

**Comment by thewebartisan7** [comment]
@afshinm Thanks, I missed that part. This solve issue of adding custom class for each cell, nice.

What about single template for one full row? 

And second one less important, is how to access column name from formatter, I can access only generated id.

Here is a jsfiddle example: https://jsfiddle.net/bjteg3zw/

**Comment by thewebartisan7** [comment]
Also another problem is that I can access in formatter() only to data in cells using row.cells[1].data
And not the whole JSON data from server. 
For example if I want to show in a cell two items of data from server, i can only do that if I add them to table.
Am I missing something?

**Comment by BenitoJedai** [comment]
@thewebartisan7 hi man i need the grid of the pic you share omg is amazing please share source sir

**Comment by thewebartisan7** [comment]
I am glad you like it. It's a commercial starter kit based on Laravel, see http://staging.laraloop.com/
At the moment is not yet released but will be soon.

**Comment by BenitoJedai** [comment]
@thewebartisan7 you can also share only source code gist of how i can implement row selections of gridjs and return array[] of ids please man i not have any idea how make this and y have one crucial project to implement this function please Man if you can thanks for all

**Comment by BenitoJedai** [comment]
@afshinm hi sir please help me with gist code how i can implement a row selection in gridjs tha return arrays of row id multi selection actions like delete etc... please help me Sir

**Comment by thewebartisan7** [comment]
In the screenshot is not using gridjs. I was not able yet to find an easy solution to handle this with gridjs. For now I have implement without any JS, and with DataTable. The problem that I am facing with gridjs is explained above and is not yet solved. The main issue for me is that all columns defined will be shown, while I need to format table differently. I saw recently was added nested header https://gridjs.io/docs/examples/nested-header, but I think that didn't solve my issue.

**Comment by afshinm** [comment]
@thewebartisan7 right yeah, `formatter` gives you the row, cell and column as a callback function but if you need the entire table, you can use custom HTTP clients https://gridjs.io/docs/examples/custom-http-client and save the payload in a global/shared variable.

**Comment by thewebartisan7** [comment]
I am not sure how a custom http client can help me, for just format data I can use server.then:

```
server: {
    url: 'http://example.com',
    then: data => {
      // return data that I want
    }
  }
```

It was now time ago when I do test, so I am don't remember correctly, but the problem was that I was not able to access data in formatter cell if this was not in `columns`. It was in data but not in columns for header... I mean this https://github.com/grid-js/gridjs/issues/245#issuecomment-692040200

I didn't test the custom http client, but seem that it just return data like server.then, but if this is missing in columns for header, I suppose I will not be able to access it using `row.cells[1].data`... or yes?
