### ISSUE TITLE
Server-Side Search doesn't work

### ISSUE THREAD

**Issue by benborla** [grid-js/gridjs#248]
**Describe the bug**
I tried to implement a server-side search using the editor on the website, I've used the pokemon API URL but it doesn't work, it only returns all the lists of the first page.

**To Reproduce**
Use this code on this URL (Server Side Search Documentatôn)[https://gridjs.io/docs/examples/server-side-search]
```javascript
const grid = new Grid({
  pagination: true,
  search: {
    server: {
      url: (prev, keyword) => `${prev}?search=${keyword}`
    }
  },
  columns: ['Name', 'URL'],
  server: {
    url: 'https://pokeapi.co/api/v2/pokemon',
    then: data => data.results.map(pokemon => [pokemon.name, pokemon.url])
  } 
});
```

**Expected behavior**
It should return the data that I am searching for, not the whole list of data.

**Comment by afshinm** [comment]
@benborla because `?search=` is not a valid parameter for that endpoint, e.g. https://pokeapi.co/api/v2/pokemon?search=abcde
