### ISSUE TITLE
Request ReloadTable

### ISSUE THREAD

**Issue by andresfdel17** [grid-js/gridjs#253]
Saludos, 

Encuentro muy útil tu librería y te agradezco el aporte.

Mi pregunta, no tienes al go para recargar la tabla?, ejemplo. Estoy usando filtros dinámicos, cómo puedo recargar la tabla al cambio de uno de estos filtros?

**Comment by BenitoJedai** [comment]
Hola amigo usas el método  forceUpdate

**Comment by BenitoJedai** [comment]
forceRender

**Comment by nachiomdq** [comment]
Hi ! I'm have troubles with forceRender method. 
I'm trying to send a query parameters, but when i refresh (through a button), query parameters are duplicated, and triplicated, and go on...

![Captura de pantalla 2020-11-19 a las 15 46 37](https://user-images.githubusercontent.com/17703028/99681469-73ae9800-2a7e-11eb-848e-1a47539b052b.png)

Table renders fine the first time, but when i select a couple of data, forceRender not works as expected... Could you tell me if i'm doing right? 

Thanks.
