### ISSUE TITLE
jQuery wrapper

### ISSUE THREAD

**Issue by afshinm** [grid-js/gridjs#27]
`$(element).gridjs({...});`

**Comment by rmkane** [comment]
I am not sure how you could incorporate it into your current build, but I assume you would just create a static jQuery wrapper that loads after `gridjs.production.min.js`.

## main.js

```js
const main = async () => {
  $('#wrapper').gridjs({
    columns: ["Name", "Email", "Phone Number"],
    data: await fetchJsonData('data.json'),
    search: true,
    sort: true
  });
};

/**
 * @description Returns a JSON promise
 * @param {string} filename
 * @returns {Promise<T>}
 */
const fetchJsonData = async (filename) => {
  return fetch(filename)
    .then(response => response.json());
};

main().then(res => null);
```

## jquery.gridjs.js

```js
/*
 * filename: jquery.gridjs.js
 */
(($) => {
  $.fn.gridjs = function(options) {
    new gridjs.Grid(options).render(this.get(0));
    return this;
  };
})(jQuery);
```

## data.json

```json
[
  ["John", "john@example.com", "(353) 01 222 3333"],
  ["Mark", "mark@gmail.com", "(01) 22 888 4444"],
  ["Eoin", "eoin@gmail.com", "0097 22 654 00033"],
  ["Sarah", "sarahcdd@gmail.com", "+322 876 1233"],
  ["Afshin", "afshin@mail.com", "(353) 22 87 8356"]
]
```

## index.html

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>A jQuery wrapper for gridjs</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tailwindcss/ui@latest/dist/tailwind-ui.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" />
    <link rel="stylesheet" href="style.css" />
    <script src="https://unpkg.com/gridjs/dist/gridjs.production.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="jquery.gridjs.js"type="text/javascript"></script>
  </head>
  <body>
    <h1 class="text-3xl font-bold text-center">jQuery Wrapper</h1>
    <div id="wrapper"></div>
    <script src="main.js" type="text/javascript"></script>
  </body>
</html>
```

## style.css

```css
:root {
  --background-color: #222;
  --foreground-color: #FFF;
}

body {
  padding: 1em;
  background: var(--background-color);
  color: var(--foreground-color);
}
```

**Comment by afshinm** [comment]
@rmkane that's it I guess, yeah! I just created this repo https://github.com/grid-js/gridjs-jquery if you like to contribute and add that to the repo.

Also, it's nice to pass the element in `$(element)` to the `from` property if it's a HTML table. see https://gridjs.io/docs/config#from

**Comment by rmkane** [comment]
> @rmkane that's it I guess, yeah! I just created this repo https://github.com/grid-js/gridjs-jquery if you like to contribute and add that to the repo.

I’ll check it out. 

> Also, it's nice to pass the element in `$(element)` to the `from` property if it's a HTML table. see https://gridjs.io/docs/config#from

That makes sense. I didn’t dig into the config that much;
just brushed the surface.

**Comment by rmkane** [comment]
I started to use Webpack, but I do not like how it adds a bunch of extra stuff to the distribution/bundle files. Maybe I misconfigured it. Im probably gonna switch to Rollup.

Anyways, I have a feature branch for the jQuery stuff. Maybe it can give people ideas?

> https://github.com/rmkane/gridjs-jquery/tree/feature/skeleton

**Comment by afshinm** [comment]
@rmkane +1 for using Rollup instead. 

That looks amazing! I'd suggest fixing the build took and merging that PR.
