### ISSUE TITLE
Server side search: no parameter sent

### ISSUE THREAD

**Issue by wolfgangmm** [grid-js/gridjs#281]
Using gridjs 2.1.0 I somehow can't get server-side search to work. The required parameter is not sent in the HTTP request and it even looks like the search.server.url function is never called. Below is my config - maybe I'm missing something simple:

```
const grid = new Grid({
                search: {
                    server: {
                        url: (prev, keyword) => `${prev}${prev.indexOf('?') > -1 ? '&' : '?'}search=${keyword}`
                    }
                },
                columns: columns,
                server: {
                    url: this.toAbsoluteURL(this.source),
                    then: data => data.results,
                    total: data => data.count
                }
            });
```

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Browser: Chrome
 - Version: 85.0.4183.121

**Comment by afshinm** [comment]
I just used this online example https://gridjs.io/docs/examples/server-side-search and the search module works for me.

Your config seems to be correct though. Can you set a debugger/console.log in the search.server.url and log `prev` and `keyword` please?

**Comment by wolfgangmm** [comment]
It turned out that my example fails because the gridjs container div is rendered inside the shadow DOM of an enclosing web component. I'm not sure about the exact reasons, but it's also not a problem to create a separate search form inside my component and manually call `forceRender()` on gridjs to update. This works for me, so happy to close this issue.

**Comment by afshinm** [comment]
great, thanks @wolfgangmm
