### ISSUE TITLE
Nested Header text collapse

### ISSUE THREAD

**Issue by im28** [grid-js/gridjs#283]
Hi there is a bug regarding the nested headers the text is displayed incorrectly when multiple nested headers are added

**To Reproduce**
const grid = new Grid({
  columns: [
      { 
        name: 'Name',
        columns: [{
          name: 'First'
        }, {
          name: 'Last'
        }]
      },
      'Email',
      { 
        name: 'Address',
        columns: [{
          name: 'Country'
        }, {
          name: 'City',
          columns: [{
            name: 'Name'
          }]
        }]
      },
      { 
        name: 'Address',
        columns: [{
          name: 'Country'
        }, {
          name: 'City',
          columns: [{
            name: 'Name'
          }]
        }]
      },
      { 
        name: 'Address',
        columns: [{
          name: 'Country'
        }, {
          name: 'City',
          columns: [{
            name: 'Name'
          }]
        }]
      },
      { 
        name: 'Address',
        columns: [{
          name: 'Country'
        }, {
          name: 'City',
          columns: [{
            name: 'Name'
          }]
        }]
      },
      { 
        name: 'Address',
        columns: [{
          name: 'Country'
        }, {
          name: 'City',
          columns: [{
            name: 'Name'
          }]
        }]
      },
      { 
        name: 'Address',
        columns: [{
          name: 'Country'
        }, {
          name: 'City',
          columns: [{
            name: 'Name'
          }]
        }]
      },
      { 
        name: 'Address',
        columns: [{
          name: 'Country'
        }, {
          name: 'City',
          columns: [{
            name: 'Name'
          }]
        }]
      },
      { 
        name: 'Name',
        columns: [{
          name: 'First'
        }, {
          name: 'Last'
        }]
      },
   ],
  data: Array(5).fill().map(x => [
    faker.name.firstName(),
    faker.name.lastName(),
    faker.internet.email(),
    faker.address.countryCode(),
    faker.address.city(),
  ])
});

![image](https://user-images.githubusercontent.com/27422200/95834242-4e3bb980-0d6f-11eb-9836-3ddb72f1af80.png)

**Additional context**
cdn: https://unpkg.com/gridjs/dist/gridjs.production.min.js

**Comment by afshinm** [comment]
You have about 20 child headers while your data represents 5 columns only. That's why the header columns don't match your data columns.

Also, to fix the width issue, simply set `width: 1000px` in your Grid.js config and that should fix the issue.
