### ISSUE TITLE
Undefined grid.config.data

### ISSUE THREAD

**Issue by BenitoJedai** [grid-js/gridjs#285]
@afshinm  Please help me assume this code example
`const grid = new gridjs.Grid({
      columns: ["id", "fecha", "origen", "destino", "precio"],
      sort: true,
      fixedHeader: true,
      height: '350px',
      server: {
        url: "http://localhost:8080/api.php/viajes?transform=1",
        then: data => data.viajes
      },
      language: {
        'search': {
          'placeholder': '馃攳 Buscar...'
        },
        'pagination': {
          'previous': 'Anterior',
          'next': 'Siguiente',
          'showing': 'Mostrando',
          'results': () => 'Registros'
        }
      }}).render(document.getElementById("wrapper"))`
Now when call a function like this:
`function falert() {
alert(JSON.stringify(grid.config.data))
}`

Return alert undefined!!!
I use gridjs latest versión

**Comment by BenitoJedai** [comment]
Sir @afshinm 
For fast abb of my issue i need know how i can get data from grid var when used server url and get the dat in grid like data.config.data

**Comment by afshinm** [comment]
@BenitoJedai It's not possible to read the table data when the data source is server-side. 

You might need to write a simple plugin to get access to the pipeline, see: https://gridjs.io/docs/plugin/basics 

What are you trying to achieve?

**Comment by BenitoJedai** [comment]
@afshinm 
Excuse me friend but after destroying and destroying all your code for almost 6 hours I have finally found the solution 😎
`grid.config.storage.get().then(function(viajes) {
alert(JSON.stringify(viajes.data))
})`
ready gets the data no matter if it is used from the server or with data There are no impossible friends 😉
And thanks for your excellent work, your library, except for my project. THANKS Friend Blessings
Add this Tip in the WebPage Sir

**Comment by BenitoJedai** [comment]
@afshinm add the trick in your gridjs webpage for all fans of this lib

**Comment by afshinm** [comment]
Awesome!
