### ISSUE TITLE
Typings for events?

### ISSUE THREAD

**Issue by jg76379** [grid-js/gridjs#288]
**Is your feature request related to a problem? Please describe.**
I can not figure out how to properly type the events emitted from Grid (https://gridjs.io/docs/examples/event-handler). Do types exist for this? It seems to return an array where [0] is the mouse click event and [1] is the instance of the Row class, but those classes don't seem to exist as global exports from the package.

**Describe the solution you'd like**
Is it possible that types can be exported for this?

**Describe alternatives you've considered**
If I am missing something and there is currently a way to import or reference these types please let me know.

**Comment by afshinm** [comment]
Evens are already typed, see https://github.com/grid-js/gridjs/blob/master/src/view/events.ts and https://github.com/grid-js/gridjs/blob/master/src/events.ts.
