### ISSUE TITLE
Allow strings to be marked safe somehow.

### ISSUE THREAD

**Issue by UNIcodeX** [grid-js/gridjs#29]
**Is your feature request related to a problem? Please describe.**
HTML code passed as a result value from JSON query, yields escaped HTML code. 

JSON:
```json
[
  [
    "fcfc73437f8182ef", 
    "2020-06-03", 
    "<img src='static/img/scans/5ed81d101351c96ec6632015.png' style='width:200px;' />"
  ], 
  ...
]
```

JS:
```javascript
new gridjs.Grid({
  columns: ["ID", "Date", "Image"],
  search: true,
  sort: true,
  pagination: {
    enabled: true,
    limit: 10,
    summary: true,
    prevButton: true,
    nextButton: true,
  },
  server: {
    url: '/examplesJSON',
    then: data => 
      data.map(
        example => [
          example[0],
          example[1],
          example[2]
        ]
      )
  }
}).render(document.getElementById("examplesWrapper"));
```
Rendered, mapped HTML from JSON request:
```html
<td class="gridjs gridjs-td">
&lt;img src='static/img/scans/5ed81d251351c96ec6632017.png' style='width:200px;' /&gt;
</td>
```

**Describe the solution you'd like**
A method to not make the strings "safe" so they can be passed in correctly rendered. Something akin in function to Jinja's `| safe` modifier?

**Describe alternatives you've considered**
I've tried using backslashes

**Additional context**

**Comment by afshinm** [comment]
Makes sense. I will push a fix soon.

**Comment by afshinm** [comment]
#49 should fix this one, too. I have added a new function, `html`, which enables us to embed HTML elements in cells. will update the docs as well.

**Comment by UNIcodeX** [comment]
Nice! Thank you.

I see updated documentation on how one would do this when used in a module, but nothing on how would one do this in line between `<script>`. This may seem self evident, but newcomers may not make the connection that simply calling `html()` as in the example will not work in this case, and that it must be fully qualified as `gridjs.html()`.

Thanks again.

**Comment by afshinm** [comment]
Makes sense. I have created this Codesandbox: https://codesandbox.io/s/gridjs-hello-world-html-ecepd?file=/src/index.js:0-301

```js
const { Grid, html } = gridjs;

new Grid({
  columns: ["Name", "Email", "Phone Number"],
  search: true,
  data: [
    ["John", "john@example.com", html("<b>(353) 01 222 3333</b>")],
    ["John", "john@example.com", html("<i>(353) 01 222 3323</i>")]
  ]
}).render(document.getElementById("wrapper"));
```

but I will add that to the docs as well.

**Comment by UNIcodeX** [comment]
Nice! I must say congratulations on a really awesome library. In my opinion it is much more ergonomic than dataTables. Also, Thank you for how responsive you've been.

**Comment by afshinm** [comment]
thank you @UNIcodeX!
