### ISSUE TITLE
Server / missing http headers in request

### ISSUE THREAD

**Issue by Kublick** [grid-js/gridjs#293]
**Describe the bug**
On server options to retrieve the data from the server, I added the header to send a validation token ; after checking the request call headers are missing

**To Reproduce**

config server in the function:
 server={{
          url: process.env.backendURL + '/api/users/',
          header: { 'x-auth-token': 'gibersih' },
          then: (data) =>
          .....
            ]),
          total: (data) => data.user.count,
        }}

Process the call in the app and you will see headers are not being added to the request

**Expected behavior**
x-auth-token should be added in the request to the backend

**Screenshots**

![image](https://user-images.githubusercontent.com/39152022/96354731-b56aae00-108e-11eb-802d-52444a70e0e8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 / WSL2 Ubuntu
 - Browser chrome
 - Version 

**Smartphone (please complete the following information):**
 - Version 86.0.42

**Comment by afshinm** [comment]
@Kublick I couldn't reproduce that bug with the latest version of Grid.js:

```
const grid = new Grid({
  columns: ['Name', 'Language', 'Released At', 'Artist'],
  server: {
    url: 'https://api.scryfall.com/cards/search?q=Inspiring',
    then: data => data.data.map(card => [card.name, card.lang, card.released_at, card.artist]),
    headers: {'x-my-header': 3}
  } 
});
```

**Comment by afshinm** [comment]
oh the key is `headers` not `header`. Sorry for the confusion. I will update the docs.
