### ISSUE TITLE
column width % rendered as px

### ISSUE THREAD

**Issue by systemcrash** [grid-js/gridjs#311]
**Describe the bug**

Set `width: '5%'` and resulting HTML is `style="width: 87px;"` - setting any % value seems to result in some px value calculated to that percent proportion of the window width. 

**To Reproduce**
Set `width` to some `%` value
```
...
    columns: [{
     id: 'thing',
     name: 'Some string',
     width: '10%'
  }, {
...
```

**Expected behavior**
Column HTML shows e.g.: `style="width: 10%;"`

https://gridjs.io/docs/config/columns

lists `width` as `px` or `%`

**Desktop (please complete the following information):**
 - FF
 - Version 82.0.1

**Comment by afshinm** [comment]
@systemcrash you can disable the `audoWidth` flag to achieve that https://gridjs.io/docs/config/autoWidth/
