### ISSUE TITLE
Need example

### ISSUE THREAD

**Issue by andresfdel17** [grid-js/gridjs#312]

**Comment by andresfdel17** [comment]
Hello, please i need a hiiden column example, to me don´t works!

**Comment by andresfdel17** [comment]
{
        className: {
          table: "table-responsive",
          th: "text-center",
          td: "text-center"
        },
        fixedHeader: true,
        sort: true,
        pagination: true,
        search: {
          server: {
            url: (prev, keyword) => {
              Var = keyword;
              return `${prev}?search=${Var}`;
            },
            method: "POST",
            body: () => {
              var FD = new FormData();
              FD.append("search", Var);
              return FD;
            },
          },
        },
        columns: [
          G.translateDT("name"),
          G.translateDT("description"),
          G.translateDT("table"),
          {
            name: G.translateDT("updated-at"),
            formatter: (_, row) => {
              return GridHtml(`${row.cells[3].data.split("T")[0]}`)
            }
          },
          {
            name: G.translateDT("actions"),
            formatter: (_, row) => GridHtml(
              `
                <div class="btn-group">
                    <a class="btn btn-sm btn-default" onclick="GetCustomField(${row.cells[4].data}, ${row.cells[5].data})" >
                        <svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                        </svg>
                    </a>
                    <a class="btn btn-sm btn-default" onclick="DeleteCustomField(${row.cells[4].data})">
                        <svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                    </a>
                </div>
              `
            )
          },
          {
            name: 'Tag',
            hidden: true
          }
        ],
        server: {
          url: G.GetUrl()["complete_path"] + "Fieldsdatatables",
          method: "POST",
          then: (data) => {
            return data.data.map((element) => {
              //aca se reescriben los valores a editar 
              return [
                element.name,
                element.description,
                element.table_,
                element.updated_at,
                element.id,
                element.tag
              ];
            })
          },

        },
        language: GridLanguage,
      }`
`

**Comment by andresfdel17** [comment]
{
        className: {
          table: "table-responsive",
          th: "text-center",
          td: "text-center"
        },
        fixedHeader: true,
        sort: true,
        pagination: true,
        search: {
          server: {
            url: (prev, keyword) => {
              Var = keyword;
              return `${prev}?search=${Var}`;
            },
            method: "POST",
            body: () => {
              var FD = new FormData();
              FD.append("search", Var);
              return FD;
            },
          },
        },
        columns: [
          G.translateDT("name"),
          G.translateDT("description"),
          G.translateDT("table"),
          {
            name: G.translateDT("updated-at"),
            formatter: (_, row) => {
              return GridHtml(`${row.cells[3].data.split("T")[0]}`)
            }
          },
          {
            name: G.translateDT("actions"),
            formatter: (_, row) => GridHtml(
              `
                <div class="btn-group">
                    <a class="btn btn-sm btn-default" onclick="GetCustomField(${row.cells[4].data}, ${row.cells[5].data})" >
                        <svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                        </svg>
                    </a>
                    <a class="btn btn-sm btn-default" onclick="DeleteCustomField(${row.cells[4].data})">
                        <svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                    </a>
                </div>
              `
            )
          },
          {
            name: 'Tag',
            hidden: true
          }
        ],
        server: {
          url: G.GetUrl()["complete_path"] + "Fieldsdatatables",
          method: "POST",
          then: (data) => {
            return data.data.map((element) => {
              //aca se reescriben los valores a editar 
              return [
                element.name,
                element.description,
                element.table_,
                element.updated_at,
                element.id,
                element.tag
              ];
            })
          },

        },
        language: GridLanguage,
      }```
```

**Comment by andresfdel17** [comment]
```javascript
{
        className: {
          table: "table-responsive",
          th: "text-center",
          td: "text-center"
        },
        fixedHeader: true,
        sort: true,
        pagination: true,
        search: {
          server: {
            url: (prev, keyword) => {
              Var = keyword;
              return `${prev}?search=${Var}`;
            },
            method: "POST",
            body: () => {
              var FD = new FormData();
              FD.append("search", Var);
              return FD;
            },
          },
        },
        columns: [
          G.translateDT("name"),
          G.translateDT("description"),
          G.translateDT("table"),
          {
            name: G.translateDT("updated-at"),
            formatter: (_, row) => {
              return GridHtml(`${row.cells[3].data.split("T")[0]}`)
            }
          },
          {
            name: G.translateDT("actions"),
            formatter: (_, row) => GridHtml(
              `
                <div class="btn-group">
                    <a class="btn btn-sm btn-default" onclick="GetCustomField(${row.cells[4].data}, ${row.cells[5].data})" >
                        <svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                        </svg>
                    </a>
                    <a class="btn btn-sm btn-default" onclick="DeleteCustomField(${row.cells[4].data})">
                        <svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                    </a>
                </div>
              `
            )
          },
          {
            name: 'Tag',
            hidden: true
          }
        ],
        server: {
          url: G.GetUrl()["complete_path"] + "Fieldsdatatables",
          method: "POST",
          then: (data) => {
            return data.data.map((element) => {
              //aca se reescriben los valores a editar 
              return [
                element.name,
                element.description,
                element.table_,
                element.updated_at,
                element.id,
                element.tag
              ];
            })
          },

        },
        language: GridLanguage,
      }
```

**Comment by afshinm** [comment]
This is perhaps because you're using a wrapper that hasn't been updated. I will update all wrappers today.
