### ISSUE TITLE
Rendering into a div with "display:none" result in non-standard width behaviour

### ISSUE THREAD

**Issue by fikrimi23** [grid-js/gridjs#326]
**Describe the bug**
I am trying to have tabs navigation with table as the content. At the initial state, only 1 content div is shown, the other has "display:none" attribute.
![image](https://user-images.githubusercontent.com/8409391/98595206-42103100-2308-11eb-828e-001b0c4653e2.png)

As I render the two table using gridjs (using new Gridjs obviously) the initially shown one is good, but when I switch to other tabs, the width seems weird, it doesn't seem to auto width itself
![image](https://user-images.githubusercontent.com/8409391/98595488-a29f6e00-2308-11eb-8aa5-06ce60d699b2.png)
![image](https://user-images.githubusercontent.com/8409391/98595524-adf29980-2308-11eb-8804-c7464eacbc65.png)

**To Reproduce**
1. Follow the hello world https://gridjs.io/docs/hello-world
2. Add `style="display:none"` to div wrapper
3. Inspect the elment
4. The width is missing

**Expected behavior**
It can be auto-width-ed itself even when display:none?

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Chromium
 - Version 86.0.4240.183 

**Additional context**
My current workaround is to render it when the hidden content is initially shown

**Comment by afshinm** [comment]
Hey @fikrimi23 

Yes, because Grid.js expects the table to be available on the page and `display: none` simply hides the table and Grid.js autoWidth function cannot find it.

**Comment by fikrimi23** [comment]
Ok thank you for confirming

**Comment by afshinm** [comment]
In order to fix this, you can either:

 - Display both table initially, bind a callback to the `ready` event of Grid.js and _then_ add the `display: none` attribute, or:
 - Set a static column.width instead if you can't display the table.
