### ISSUE TITLE
Auto width does not take in consideration width of sort icon

### ISSUE THREAD

**Issue by viliamzigo** [grid-js/gridjs#329]
**Describe the bug**

Auto width does not take in consideration sort icon. Thus, sort icon falls into next line (as in screenshot).

**To Reproduce**

1. Go to gridjs.io and find live editor
2. Allow sort and autoWidth
3. Change headers like in screenshot

**Expected behavior**

Should automatically calculate width of column with respect to sort icon and in never fall into new line.

**Screenshots**

**sort: true -> Looks awful**

![image](https://user-images.githubusercontent.com/26348944/98729165-ca3f1680-239a-11eb-9d57-c98fd8238b02.png)

**sort: false -> Works nicely**

![image](https://user-images.githubusercontent.com/26348944/98730259-50a82800-239c-11eb-8738-06e112bbc4cd.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 86

**Comment by afshinm** [comment]
I can look into that @viliamzigo. thanks for flagging.

**Comment by SukkaW** [comment]
Is the issue being worked on? I am facing the same issue here.

**Comment by afshinm** [comment]
I will send a patch today. thanks for flagging @SukkaW

**Comment by afshinm** [comment]
This commit should address this issue https://github.com/grid-js/gridjs/commit/d2df219c8b7981ff6958c1a2c5f7577c9bb6d532
