### ISSUE TITLE
HTML escapes should be processed when importing from a HTML table

### ISSUE THREAD

**Issue by xguerin** [grid-js/gridjs#338]
**Describe the bug**
HTML escape sequences render verbatim when importing from a HTM table.

**To Reproduce**
1. Using "From HTML table" example
2. Replace "John" by "John &amp; Jane" in the `<td>`
3. See error

**Expected behavior**
The escape sequence should be processed.

**Additional context**
I will submit a PR based on https://stackoverflow.com/a/34064434.

**Comment by afshinm** [comment]
Thanks @xguerin.
