### ISSUE TITLE
A click on 'No matching records found' triggers 'rowClick' and 'cellClick' events.

### ISSUE THREAD

**Issue by Thimows** [grid-js/gridjs#345]
I noticed that when the 'No matching records found' alert is clicked that it triggers the 'rowClick' and 'cellClick' events. Is there a way to stop this from happening? 

![ezgif-3-a4d4d6b25ee3](https://user-images.githubusercontent.com/62159496/100003891-05900b00-2dc7-11eb-8fdf-cf270de348df.gif)

**Comment by afshinm** [comment]
Thanks for the report @Thimows. I can work on that.

**Comment by aronmi** [comment]
@afshinm i think this one can be closed since #363 is merged.
