### ISSUE TITLE
Question: Getting the actual data object in the formatter callback

### ISSUE THREAD

**Issue by sehwol** [grid-js/gridjs#348]
Is there an official way to get the row from `config.data` in the `TColumn.formatter` callback instead of just the `Row class` object?

## Details

`TColumn.formatter` takes the callback below

```typescript
(cell: TCell, row: Row, column: TColumn) => ComponentChild;
```

When we need to make a button to get the data for that row, it would be nicer to get the actual JSON in `config.data` which contains all the key value pairs. `row: Row` only includes the cells rendered and the actual key doesn't exist in a `cell` (only the UUID `_id`).

Sorry if I misunderstood the documentation.

**Comment by afshinm** [comment]
@sehwol the `row` parameter should already have the key value you need. simply run `row.cells()` to get all the cells or `row.cell(2)` to get the 3rd cell of that row, see https://github.com/grid-js/gridjs/blob/master/packages/gridjs/src/row.ts#L18-L20

**Comment by Elcaten** [comment]
Let's say I init the grid using the following config:

```
this.grid = new Grid({
  columns: [
    { name: 'Name', id: 'name' },
    { name: 'Email', id: 'email' },
    {
      name: 'Actions',
      formatter: (_, row) => {
        return h( 
          'button',
          { onClick: () => console.log(JSON.stringify(row, null, 2)) },
          'Log'
        );
      },
    },
  ],
  data: [{ name: 'John Doe', email: 'john@doe.icu' }],
}).render(this.table.nativeElement);
```

Upon clicking on the `log` button I will receive the following `console.log` output:

```
{
  "_id": "14e79d9d-bd12-472d-a3c8-f53e6808497d",
  "_cells": [
    {
      "_id": "5fb9ed61-e67c-43b6-bbc4-0eb54e19342b",
      "data": "John Doe"
    },
    {
      "_id": "483b09a4-4595-4a95-be5b-bfd4cf97e9f5",
      "data": "john@doe.icu"
    },
    {
      "_id": "d7d05d3a-3d42-4acd-b487-f39fcdeb3caf"
    }
  ]
}
```
As you can see, there is no way of accessing row data using `'name'` and `'email'` keys I used in column definitions.
I'm thus forced to using indexes to access cells datum, which is prone to errors.
Is there any workaround? Thanks!
