### ISSUE TITLE
Site Examples Broken and Plugins Not Rendering

### ISSUE THREAD

**Issue by lrpatterson** [grid-js/gridjs#353]
**Describe the bug**
When I try to add a custom plugin it never renders to `PluginPosition.Header` location.
**To Reproduce**
1. Go to 'https://codepen.io/Lrpatterson89/pen/jOMbaeb'
2. You should see that the plugin does not render `Hello world!`

**Expected behavior**
I expect the word `Hello world!` to render to the header position

**Additional context**
I also noticed that the simple plugin examples on the site are also broken

![image](https://user-images.githubusercontent.com/41905851/100891821-acd80680-3487-11eb-97b3-94dfd9dd0a9e.png)

**Comment by afshinm** [comment]
Yep, sorry about that. Looks like I have to update the docs. The correct usage is:

```javascript
import {h, Grid, PluginPosition} from 'https://cdn.skypack.dev/gridjs';


function MyPlugin() {
  return h('h1', {}, 'Hello world!');
}
  
const grid = new Grid({
  columns: ['Name', 'Email', 'Phone Number'],
  data: [
    ['John', 'john@example.com', '(353) 01 222 3333'],
    ['Mark', 'mark@gmail.com',   '(0) 22 888 4444'],
  ]
});
  
grid.plugin.add({
  id: 'myplugin',
  component: MyPlugin,
  position: PluginPosition.Header,
});

grid.render(document.getElementById("wrapper"))
```

**Comment by afshinm** [comment]
Just updated the docs as well. Thanks for the heads up @lrpatterson
