### ISSUE TITLE
Dark Mode & coloring data

### ISSUE THREAD

**Issue by erceamet** [grid-js/gridjs#360]
Hello,

I would like to be able to change the colour of the whole table. So far I only managed to change the colour of the table header (I am using React for this). I have attempted to set a colour for the td or the whole table but nothing much has changed. Unless I am doing something wrong.

I would also like to be able to dynamically set a colour for some of the data in the table. For example, in the image attached below, I would like to display certain marks in a certain colour.

This is what I'm using so far.
```
sty = {
    table: {
      border: "3px solid #ccc",
    },
    th: {
      "background-color": "rgba(0, 0, 0, 0.1)",
      color: "#fff",
      "border-bottom": "3px solid #ccc",
      "text-align": "center",
    },
    td: {
      "text-align": "center",
    },
  };
```

Please let me know if there are already solutions for my issues. Thank you for your time!

![image](https://user-images.githubusercontent.com/33298952/101531537-538e3c80-398b-11eb-8186-8751eb246dbe.png)

**Comment by afshinm** [comment]
hey @erceamet. yeah I have been working on this feature for a while but it's not released yet. I will hopefully release it in the next few days.

**Comment by erceamet** [comment]
> hey @erceamet. yeah I have been working on this feature for a while but it's not released yet. I will hopefully release it in the next few days.

Thank you for your quick reply. May I ask which feature you're talking about? Is it the dark mode?
I have attempted to change the colors on the gridjs.io and this is what I get
![image](https://user-images.githubusercontent.com/33298952/101539794-fac4a100-3996-11eb-9b5e-abd5b1b106d5.png)
It seems that it's only changing the color of the even rows (if that makes sense). I do understand this is not a necessary feature for the functionality but it would be nice to have. Thank you

**Comment by afshinm** [comment]
That seems like the default CSS style for table rows on gridjs.io website (i.e it's not Grid.js CSS)

**Comment by afshinm** [comment]
You can use these CSS class / style configs for td/th though: https://github.com/grid-js/gridjs/blob/master/packages/gridjs/src/config.ts#L56-L71

**Comment by erceamet** [comment]
> That seems like the default CSS style for table rows on gridjs.io website (i.e it's not Grid.js CSS)

ah okay got it



> You can use these CSS class / style configs for td/th though: https://github.com/grid-js/gridjs/blob/master/packages/gridjs/src/config.ts#L56-L71

I will rather wait for the feature release as I am not quite sure how that would work. But thank you for your time.

**Comment by erceamet** [comment]
Managed to solve the problems. Both the colouring of the td and dynamically colouring the table content. Solved based on this: https://gridjs.io/docs/examples/stock-market

I am leaving the code below in case anyone has the same problems as me.

```
class DashboardMarks extends Component {
  data = [];

  sty = {
    table: {
      border: "3px solid #90E0EF",
      color: "#fff",
    },
    th: {
      "background-color": "#48CAE4",
      color: "black",
      "border-bottom": "3px solid #90E0EF",
      "text-align": "center",
    },
    td: {
      "background-color": "#21212c",
      color: "#fff",
      "text-align": "center",
    },
    footer: {
      "background-color": "#48CAE4",
      color: "#fff",
    },
  };

  displayMarkTable = () =>
    this.props.mcqTests.map((test) => {
      let info = [];
      return (
        <div>
          <h3 className={styles.Title}>{test.mcq_title}</h3>
          {this.props.marks.forEach((mark) => {
            let array = [];
            if (mark.mcq_id === test.mcq_id) {
              array = [
                mark.mark,
                new Date(mark.submit_date).toLocaleDateString(),
                mark.submit_hour,
              ];
              info.push(array);
            }
          })}
          {
            <Grid
              data={info}
              style={this.sty}
              columns={[
                {
                  name: "Mark",
                  formatter: (cell) => {
                    return h(
                      "b",
                      {
                        style: {
                          color:
                            cell >= 40
                              ? cell <= 70
                                ? "yellow"
                                : "green"
                              : "red",
                        },
                      },
                      cell
                    );
                  },
                },
                "Date",
                "Hour",
              ]}
              sort={true}
              search={true}
              pagination={{
                enabled: true,
                limit: 6,
              }}
            />
          }
        </div>
      );
    });

  render() {
    return (
      <div>
        <h2 className={styles.Title}>Marks</h2>
        <div className={styles.Marks}>
          Marks under 40 (exclusive) represented with{" "}
          <span className={styles.Fail}>red</span>, between 40 (inclusive) and
          70 (exclusive) with <span className={styles.Pass}>yellow</span>, and
          above 70 (inclusive) with{" "}
          <span className={styles.Excellent}>green</span>.
          {this.props.gotTests & this.props.gotMarks
            ? this.displayMarkTable()
            : null}
        </div>
      </div>
    );
  }
}
```

Final outcome
![image](https://user-images.githubusercontent.com/33298952/101546305-7f67ed00-39a0-11eb-85c7-53ceddcb0ea4.png)

I didn't manage to change the text colour in the footer where it shows "Showing X to X of X results". Thanks for the support.

**Comment by afshinm** [comment]
Awesome! thanks
