### ISSUE TITLE
Nested JSON problem

### ISSUE THREAD

**Issue by hubertzawada** [grid-js/gridjs#391]
Hi,

I have nested JSON which I can't show via grid.js

```{
  "status": "SUCCESS",
  "orders": [
    {
      "order_id": "242317330",
      "order_status_id": "16749",
      "date_in_status": "1610540059",
      "date_add": "1610538711"
    }
  ]
}
```

I tried like this:
```columns: [{
    data: (row) => row.orders.order_id,
    name: 'order_id'
  }, {
    data: (row) => row.orders.order_status_id,
    name: 'order_status_id'
  }, {
    data: (row) => row.orders.date_in_status,
    name: 'date_in_status'
  }, {
    data: (row) => row.orders.date_add,
    name: 'date_add'
  }]
```

I figure out that is because values in "orders" are in [ ], but data comes from API, so I cannot modify it. Can you help me with this?

Regards,
Hubert

**Comment by afshinm** [comment]
Do you need to load the entire JSON though? it feels like you want to create a table for the `orders` array. In this case, simply pass the `orders` array directly to Grid.js instead of selecting the rows in the `data` callback.

**Comment by hubertzawada** [comment]
Thanks for quick reply. I confirm that I need only data from orders array. How to pass only orders array? I can't modify JSON, because it is a response from external API.

**Comment by afshinm** [comment]
You can use the `then` callback in the `server` section to filter your data and pass the `orders` array to Gridjs, example: https://gridjs.io/docs/examples/server
