### ISSUE TITLE
Incorrect display when making an unsuccessful search while some columns are hidden

### ISSUE THREAD

**Issue by zerotrac** [grid-js/gridjs#394]
**Describe the bug**

When some columns are hidden and we try to make an unsuccessful search (i.e. "No matching records found"), the columns will display incorrectly.

**To Reproduce**
1. Go to [Basic - Search](https://gridjs.io/docs/examples/search) and make use of the first sample code.
2. Modify the columns code to `columns: ['Name', {name: 'Email', hidden: true}, 'Phone Number'],` in order to hide the `Email` column.
3. Make an unsuccessful search, e.g. "Alice", the `Name` column will be compressed while the `Phone Number` column moves to the left.
4. This problem will be significant when some columns are sortable. We can see the sort triangle buttons also move to the left with the columns.

**Expected behavior**

The columns should keep their width when encountering an unsuccessful search.

**Screenshots**

![image](https://user-images.githubusercontent.com/15974765/104850556-c1cf0300-592a-11eb-95f0-970e2a57d2b5.png)

**Desktop (please complete the following information):**
 - OS: [macOS Catalina]
 - Browser [chrome]
 - Version [87.0.4280.141]

**Comment by afshinm** [comment]
I will send a patch asap.

**Comment by goellner** [comment]
can I help here somehow?

**Comment by goellner** [comment]
sorry to question about this again, but is there any chance, that a fix could be implemented this week? I tried to get this running locally, but have no idea how to set up a test environment locally which includes the local package.

**Comment by afshinm** [comment]
Apologies for the delay everyone. I have been dealing with some personal issues since a few weeks ago.

I just pushed this change https://github.com/grid-js/gridjs/commit/1f8f3a8bbbf4fbf8dda49377ad1f00c529560e90 which should fix the bug. A new version will be released today.
