### ISSUE TITLE
Using an custom component for the search placeholder

### ISSUE THREAD

**Issue by UserSina** [grid-js/gridjs#401]
I have the following using react:

```JAVASCRIPT
import { Grid, _ } from 'gridjs-react';

<Grid
...
    language={{
      search: {
        placeholder: '🔍 Search...',
      },
    }}
/>
```

**I'd like to use a custom component instead of a string as a placeholder:**
```JAVASCRIPT
import { Grid, _ } from 'gridjs-react';

<Grid
...
    language={{
      search: {
        placeholder: _(<i className="fa fa-search">Search me</i>),
      },
    }}
/>
```

**Additional context**
If possible, I'd like to be able to customize the whole div that contains the search bar to be able to achieve something like this:

![gridjs](https://user-images.githubusercontent.com/44204957/105419038-5d6bb680-5c3e-11eb-97a0-c258407332b2.jpg)

**Comment by afshinm** [comment]
@UserSina `placeholder` attribute can be a string only, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefplaceholder

You can also use custom CSS rules to move the search layer (e.g. using `float: right` or `flex`).
