### ISSUE TITLE
Add class to th and td

### ISSUE THREAD

**Issue by goellner** [grid-js/gridjs#405]
**Is your feature request related to a problem? Please describe.**
It would be great to add a custom class per column basis, to add something like `text-right` to columns, to that the` th` and `td` are right aligned.

**Describe the solution you'd like**
Custom setting for columns, to add a class to `th` and `td` of a column.

**Describe alternatives you've considered**
I have tried the `attributes` param, but this only sets it on the `td`.

**Comment by afshinm** [comment]
@goellner `column.attributes` is added to `th` as well. You can use this function to add custom classNames to your elements. See this example as well: https://gridjs.io/docs/examples/cell-attributes
