### ISSUE TITLE
Example for PluginPosition.Cell

### ISSUE THREAD

**Issue by nagavardhanraju** [grid-js/gridjs#407]
Can anybody please share an example for `PluginPosition.Cell`?

**Comment by afshinm** [comment]
The Row Selection plugin is a Cell plugin: https://gridjs.io/docs/examples/row-selection

(this line https://github.com/grid-js/gridjs/blob/4e5e6a3482a25644c89e3dc1ffde1c1a13ad7dea/packages/gridjs/src/header.ts#L189 finds all cell plugins and renders a virtual cell using that plugin)
