### ISSUE TITLE
Plugin disappear after forceRender

### ISSUE THREAD

**Issue by wanlwanl** [grid-js/gridjs#414]
**Describe the bug**

**To Reproduce**
1. add plugin from https://gridjs.io/docs/plugin/writing-plugin
2. render a table
3. force render https://gridjs.io/docs/examples/force-render

**Expected behavior**

display `Hello World!` after force render

**Screenshots**

**Desktop (please complete the following information):**
 - OS: window
 - Browser: chrome

**Comment by wanlwanl** [comment]
```
grid.config.data.push(row);
  grid.forceRender();
```
works, but the state inside my pulgin get reset

**Comment by afshinm** [comment]
@wanlwanl did you find a solution for this?

**Comment by azlkiniue** [comment]
Hello @wanlwanl 
I have the exact same problem, could you please explain how to fix that?

**Comment by wanlwanl** [comment]
@azlkiniue @afshinm 
you need to add your own plugin (do not add built-in plugin like `search`, `pagination`) again in `updateConfig`, even they are not changed.
e.g.
``` js
grid.updateConfig({
    ...
    plugins: [plugin] 
})
grid.forceRender()
```
