### ISSUE TITLE
The scroll position is reset by adding data

### ISSUE THREAD

**Issue by antennix** [grid-js/gridjs#427]
**Describe the bug**
The scroll position is reset by adding data

**To Reproduce**
1.`fixedHeader:true`,and make the data scrollable
2.Scroll vertically to the middle
3.append data and re-render
4.scroll position moves to the top

**Expected behavior**
I want to keep the scroll position, but it moves to the top

looking for a nice solution, is there a good way?

**Comment by afshinm** [comment]
I see. when you re-render your Grid.js, it basically removes all existing elements on the page and creates new ones. That's why your scroll position resets after `forceUpdate()`.

If you only need to add new rows to your table, I can work on a new function to update the internal datasource only.
