### ISSUE TITLE
Dynamic "Sr. No" like column?

### ISSUE THREAD

**Issue by shanmukhateja** [grid-js/gridjs#451]
**Is your feature request related to a problem? Please describe.**
It would be wonderful to have a dynamic "Sr. No" column for tabular data. I work with lots of tabular content using pagination and it would really help if there was a way to have a **dynamically generated** index column as the first column of the table.

**Describe the solution you'd like**
```typescript
config = {
   columns: [
      {
        name: 'ID',
        isIndexColumn: true            // something like this maybe?
      },
      "First Name",
      "Last Name"
   ],
  
```

**Describe alternatives you've considered**
I couldn't find any :(

**Additional context**
n/a

**Comment by afshinm** [comment]
This feature is not something that Grid.js should provide but it's very straightforward to achieve using a Row Formatter function and keeping an internal counter, https://gridjs.io/docs/examples/cell-formatting

**Comment by aphavichitr** [comment]
@afshinm do you have an example of this internal counter? 

> This feature is not something that Grid.js should provide but it's very straightforward to achieve using a Row Formatter function and keeping an internal counter, https://gridjs.io/docs/examples/cell-formatting
