### ISSUE TITLE
Manually set loading status

### ISSUE THREAD

**Issue by igoro00** [grid-js/gridjs#455]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I'd like to be able to set loading state manually with something like `loading={true}`(in React at least). It'd allow me to download data independently of the UI and just switch a flag when it's done.

**Describe alternatives you've considered**
I thought of returning a Promise that never resolves and when it's all downloaded I return the actual data on the next rerender. But then I started feeling bad for my and my users' computers so for now I don't use the loading feature at all and display an empty table until it's loaded.

**Comment by ubergeoff** [comment]
Instead of returning a promise that never resolves.

Why not resolve the Promise once you have your data.

EXAMPLE:

```
this.grid = new Grid({
            search: this.search,
            columns: this.columns,
            data: () =>
                new Promise((resolve) => {
                    this.resolver = resolve;
                })
        });
```

And then at some point later in time - when your data resolves:

```
if (changes.data?.currentValue && this.isLoading && this.resolver) {
            this.isLoading = false;
            this.resolver(this.data);
 }
```

Does this help..?

**Comment by ubergeoff** [comment]
But yes - it would be even more helpful if there was some sort of flag/property that we could set to we could manage the loading state outselves....

**Comment by afshinm** [comment]
I agree with @ubergeoff that you can return a Promise object and resolve it when your data is ready. When the Promise object is in pending state, Grid.js renders the loading bar. Does that make sense?

**Comment by joepagan** [comment]
@afshinm I would also like to be able to do manually set a loading state, as I am handling the fetch at a higher component level, not using your promise solution in the data property function.

**Comment by teocci** [comment]
GridJS is a UI simplifier right?, that is the idea. So it is focus on give you tools that helps you to give the  user a better experience using a table. So keeping this point in mind, yeah the table is nice beautiful, simple and when u choose it to implement it in to your project so something simple is perfect, but if the user ask you some simple UI stuff like selecting all rows, or giving a checkbox to select some rows it is a nightmare. Moreover, if you need to deal with data, this is an Interface, how you get the data here or the flow of the data it can be so complex but, the GridJS handling is oversimplified that does not help you to get a simple event like `loaded`, or `loading`. I will give you and example, we have data that has an `amount` column I want to know how many rows with column `amount` less that 100 are in this table? so for that I need to wait until the data is loaded. Of course, I can add a hidden column and put a `boolean` true if is less than 100 and false if not. OrAdd some format to the column `amount`. But I want to change the color of the rows with less than 100. This kind of flow needs hooks over the life cycle of the instance. And a clear table feature.
