### ISSUE TITLE
Supporting a table with grouping headers.

### ISSUE THREAD

**Issue by rouilj** [grid-js/gridjs#456]
It is not clear that grid-js can handle the following use case.
I have existing tables that include a header for common properties (group header). All items with that common property
are grouped together under that header row. For example:

<img width="737" alt="table_with_groups" src="https://user-images.githubusercontent.com/3751752/111057031-3bc6c880-8452-11eb-884e-55246efc4a8e.png">

When sorting this table it should respect the group headers. So if I sort by Activity, the item with id 1 should end up under
the Routine table row and not at the top of the table.

Currently sorting is done by a request to the server, but I would like to provide the option for client side sort/multisort.

Is this use case something that can be handled by grid-js, or is it out of scope?

Thanks.

-- rouilj

**Comment by afshinm** [comment]
@rouilj have you seen this example https://gridjs.io/docs/examples/nested-header?

**Comment by rouilj** [comment]
I did. Sorry, I should have mentioned that I had seen the example.

There are two things that don't match up with my use case.

  1) In the example the primary and secondary headers (name, first/last) are all at the top of the table. In my use
      case grouping headers are in the middle of the table.
  2) In the example the secondary headers are underneath a main header (e.g. name has subheads of first and last). In
      my use case the header  spans multiple top level headers rather than splitting a top level header.

-- rouilj
