### ISSUE TITLE
Question: How the gridjs is extensible?

### ISSUE THREAD

**Issue by ok2ju** [grid-js/gridjs#46]
It feels to me like Gridjs has a lack of documentation about extensibility. Could you describe how Gridjs is extensible, please?

**Comment by afshinm** [comment]
Grid.js has an internal pipeline which is used to process, refine and then feed the final result set into the Virtual DOM. This pipeline should be very extensible (you can create your own pipeline processor and attach it to a Grid.js instance with using the config object (e.g. `config.pipeline.register(...)`). See https://github.com/grid-js/gridjs/tree/master/src/pipeline

The presentation part (aka Virtual DOM) is something that I'm still working on to improve and add more options to. In general, I agree that we should document these details. I will make sure to extend and update the docs.
