### ISSUE TITLE
JS in gridjs.html

### ISSUE THREAD

**Issue by lofcz** [grid-js/gridjs#470]
**Is your feature request related to a problem? Please describe.**
Currently gridjs.html does not support <script> tags, hence `gridjs.html("<script>alert(1)</script>")` does nothing.

**Describe the solution you'd like**
gridjs.html would support inner <script> tags to execute JS. Often it is useful to exec JS code on cells, for example to initialize tooltips, etc.

**Describe alternatives you've considered**
Do nothing.

**Comment by afshinm** [comment]
It should be possible. See https://codesandbox.io/s/gridjs-js-in-cells-6p9bw?file=/src/index.js
