### ISSUE TITLE
event.ts Tip link is broken

### ISSUE THREAD

**Issue by zacharyarrington** [grid-js/gridjs#476]
I receive a 404 when I click on the Green tip bar on the bottom of this page --  https://gridjs.io/docs/examples/event-handler

Cannot see the different events

**Comment by zacharyarrington** [comment]
https://github.com/grid-js/gridjs/blob/master/src/events.ts

**Comment by afshinm** [comment]
The correct link is https://github.com/grid-js/gridjs/blob/master/packages/gridjs/src/events.ts -- I will update that page.

**Comment by sabatale** [comment]
@afshinm  FYI. Broken again.
