### ISSUE TITLE
Number of results per page

### ISSUE THREAD

**Issue by pcambra** [grid-js/gridjs#501]
**Is your feature request related to a problem? Please describe.**
It would be very handy to expose to the user the number of results per page that are displayed

**Describe the solution you'd like**
A configurable list of number of results (i.e. 6/12/24) that would be displayed on the gridjs header next to the search input.

**Comment by LightwithoutLisonlyight** [comment]
Hi, 
That's cool, but I think that you're asking for the same feature of this one:
https://github.com/grid-js/gridjs/issues/328

If I guessed, please close the issue, this way we can help the creator in the problem solving process

**Comment by pcambra** [comment]
Ah it's related but I guess this is more about having the pagination exposed, I'm closing this one and adding the remark int that one, thanks!
