### ISSUE TITLE
Pagination don't work with server side search

### ISSUE THREAD

**Issue by vittoh** [grid-js/gridjs#524]
implement pagination and search pointing to the url of the server, but when I get the search data, the pagination concating &?page that causes an error for the next page.

**http://localhost:8000/api/ubicaciones/location_list/?store=1114&?page=1**

I need to replace **"?page"** with **"page"**

somehow?

![image](https://user-images.githubusercontent.com/18142739/116178965-6f993d00-a6e4-11eb-8fa7-d7faaa90822a.png)

**Comment by afshinm** [comment]
This question is more about string manipulation in JavaScript. You can either do a string replace or use an actual URL builder lib (e.g https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) and append your search params to the URL object (and pass the string to Grid.js).
