### ISSUE TITLE
Change Preact for Svelte?

### ISSUE THREAD

**Issue by frederikhors** [grid-js/gridjs#545]
The work you have done on this project leaves you speechless with wonder.

I was wondering if instead of using Preact (which is a VDOM with non-compiled library) you had thought of using [Svelte](https://svelte.dev/) (which is without VDOM and would allow you to compile ad-hoc, therefore smaller size and more speed)?

**Comment by afshinm** [comment]
Thank you @frederikhors.

I haven't looked into Svelte and I don't know much about it but that would require changing some core parts of Grid.js. I initially developed Grid.js assuming that Preact will be the rendering template and therefore changing that part is not a trivial task. But I appreciate your suggestion, this is something that we can look into in the future.
