### ISSUE TITLE
The row button style depends on tailwind to work

### ISSUE THREAD

**Issue by beetcb** [grid-js/gridjs#560]
**Describe the bug**
I followed the documentation along the way, there is no mention of the need to import additional tailwindcss.

**To Reproduce**
Just follow the docs example: https://gridjs.io/docs/examples/row-buttons

Here you use tailwind ( Maybe it is a good idea to demonstrate about the external css  ？ )
```js
formatter: (cell, row) => {
  return h('button', {
    className: 'py-2 mb-4 px-4 border rounded-md text-white bg-blue-600',
    onClick: () => alert(`Editing "${row.cells[0].data}" "${row.cells[1].data}"`)
  }, 'Edit');
}
```

**Comment by afshinm** [comment]
I'm not quite sure if I understand this issue. Grid.js does not depend on Tailwind (or any other libs). Your button should work even if you remove the `className` attribute.

**Comment by beetcb** [comment]
@afshinm 
Sorry to bother you, but when I actually use it, the button style is indeed different from the sample, so if you could please take a look at the code and tell me what's wrong, I would be very grateful.

[Here is the demo for reproducing](https://codepen.io/beetcb/pen/VwpxbBB)

It shoud be: 

![image](https://user-images.githubusercontent.com/63141491/120895383-48bd1780-c64f-11eb-9029-bdb9d6137d26.png)

Yet this is what I get:

![image](https://user-images.githubusercontent.com/63141491/120895489-b1a48f80-c64f-11eb-94a2-e7bb7c52a90f.png)

**Comment by afshinm** [comment]
@beetcb this is just a styling issue. When you say "is indeed different from the **example**" do you mean the examples on gridjs.io? We use TailwindUI on gridjs.io (the Grid.js website/doc) but that functionality is not available on Grid.js (the Grid.js library). You need to manually include the Tailwind CSS to fix that.

**Comment by beetcb** [comment]
> do you mean the examples on gridjs.io

Yes, this is exactly what I meant, and I suggest you specify this condition in the documentation if possible.

Thank you for the answer!  @afshinm

**Comment by afshinm** [comment]
Makes sense! thanks.

**Comment by beebase** [comment]
So is there an example in the docs how to include tailwind?

**Comment by dustinwelch** [comment]
I found that adding a style to the button also works:
`formatter: (cell, row) => {
          return gridjs.h('button', {
            style:{
              'background-color': 'rgba(13, 110, 253, 0.7)',
              color: '#FFF',
              border:'1px solid #000',
              'border-radius': '3px'
              },
            onClick: () => function() 
          }, 'Edit');
        }`
