### ISSUE TITLE
GridJsConfig is not found

### ISSUE THREAD

**Issue by rohithkumar001** [grid-js/gridjs#565]
when i add this code in my app.component.ts
`import { GridJsConfig } from "gridjs-angular";`

an error comes GridJsConfig is not found in gridjs-angular. 
I'm using Angular 10 
https://github.com/grid-js/gridjs-angular/issues/89
Here is another similar issue

**Comment by salamaashoush** [comment]
this is a duplicate you can close it, I already explained how to fix it there https://github.com/grid-js/gridjs-angular/issues/89,

**Comment by rohithkumar001** [comment]
okay, Thank you!
