### ISSUE TITLE
posData with filter function with gridjs

### ISSUE THREAD

**Issue by origin2821** [grid-js/gridjs#572]
**I am coding for filter function in Grid. I want to pass an object with name, departmentId, positionId to the control file, but I don't see any way but like so:**

>server: {
>url: (prev, page, limit) => {
>>      return `${prev}rows=${limit}&page=${limit*page}&sort=${sort}&order=${order}&name=${name}
>>                  &departmentId=${departmentId}&positionId=${positionId}`;
>>          }
>>       },
>>      }, 
I feel I want to ask is there a way to upload in this format:
``
postData: {
    name: name, 
    departmentId: departmentId, 
    positionId: positionId
}
``
and just return `${prev}.`

**Comment by afshinm** [comment]
You can use the `body` config to send your data, see: https://gridjs.io/docs/config/server
