### ISSUE TITLE
Support html content when using "from"

### ISSUE THREAD

**Issue by florentsolt** [grid-js/gridjs#59]
**Is your feature request related to a problem? Please describe.**
Thanks to the new `html()` helper used in the `formater` we can easily display html in cells. But it is stil not the case when using `from`

**Describe the solution you'd like**
The idea is to automatically setup a html formater when `from` is used.

**Describe alternatives you've considered**
I've tried to used `from` with a custom `columns` definition, it does not seem to work.

**Comment by afshinm** [comment]
@florentsolt fixed in 1.4.2!

**Comment by florentsolt** [comment]
@afshinm thanks a lot!
