### ISSUE TITLE
Width of table is much smaller than header/footer when no data is provided

### ISSUE THREAD

**Issue by wanlwanl** [grid-js/gridjs#597]
**Describe the bug**
table has small width when no data if you set `resizable: true`

**To Reproduce**
1. use this code (empty for `data`):
```js
<!DOCTYPE html>
<html lang="en">
  <head>
    <link
      href="https://cdn.jsdelivr.net/npm/gridjs@4.0.0/dist/theme/mermaid.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div id="wrapper"></div>

    <script src="https://cdn.jsdelivr.net/npm/gridjs@4.0.0/dist/gridjs.production.min.js"></script>
    <script>
        new gridjs.Grid({
  columns: ['Name', 'Email', 'Phone Number'],
  data: [
  ],
  resizable: true,
  sort: true
}).render(document.getElementById("wrapper"));
    </script>
  </body>
</html>

```

**Expected behavior**

table has the same width as footer/header when no data

**Screenshots**
notice that footer is 100% width, while the table is not.
![image](https://user-images.githubusercontent.com/38236089/120960480-7fe61280-c78e-11eb-8fb2-0866dedb91f8.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Comment by afshinm** [comment]
I see. Grid.js calculate the table width based on the columns data. What you need in this case is a custom `width` for each column. Is this acceptable for you?

**Comment by wanlwanl** [comment]
oh, I found a workaround:
```js
data: [
  [],  
],
```

**Comment by wanlwanl** [comment]
I found another problem:
initial:
![image](https://user-images.githubusercontent.com/38236089/121172587-7215b780-c88a-11eb-932b-0e27aa39a53a.png)

if I resize col `a` to make it has smaller width, the col `b` cannot take the rest of the row:
![image](https://user-images.githubusercontent.com/38236089/121172769-a0939280-c88a-11eb-956f-dbfb96ea3395.png)

Is this by design?

**Comment by afshinm** [comment]
I guess that's because your table width is set to  `100%` which is the default width. For instance, set `width: 500` in your main config and see if it helps, e.g:

```
const grid = new Grid({
  columns: ['Name', 'Email', 'Phone Number'],
  data: [
    ['John', 'john@example.com', '(353) 01 222 3333'],
    ['Mark', 'mark@gmail.com',   '(01) 22 888 4444']
  ],
  width: 500,
  resizable: true
});
```

**Comment by wanlwanl** [comment]
I still need to use 100% since there are too many columns...

**Comment by zynth17** [comment]
i have the same problem and i work with server side data, is there any workaround on this one with server side data?

**Comment by zynth17** [comment]
well no problem, i found a simple work around using css.
just add this to the css.
```css
.gridjs-table{
    min-width: 100%;
}

```

**Comment by wanlwanl** [comment]
> well no problem, i found a simple work around using css.
> just add this to the css.
> 
> ```css
> .gridjs-table{
>     min-width: 100%;
> }
> ```

Thanks! It works
