### ISSUE TITLE
unexpected large file size (8x) at "unpkg.com" today June 9 2021

### ISSUE THREAD

**Issue by i-am-al-x** [grid-js/gridjs#609]
**Describe the bug**
The file sizes at "unpkg.com" are unexpectedly large.  For example gridjs.js" is 511K.
I noticed this yesterday, June 8, 2021.  The problem persists today, June 9.

**To Reproduce**

    $ curl -o gridjs.js https://unpkg.com/browse/gridjs@5.0.1/dist/gridjs.js 
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  499k    0  499k    0     0   903k      0 --:--:-- --:--:-- --:--:--  902k

    $ ls -l gridjs.js
    -rw-r--r--  1 somebody  staff  511849 Jun  9 10:34 gridjs.js

More generally:

    $ ls -l 
    total 5088
    -rw-r--r--  1 somebody  staff  511849 Jun  9 10:34 gridjs.js
    -rw-r--r--  1 somebody  staff  520361 Jun  8 18:28 gridjs.js.map
    -rw-r--r--  1 somebody  staff  513083 Jun  8 18:29 gridjs.module.js
    -rw-r--r--  1 somebody  staff  520771 Jun  8 18:29 gridjs.module.js.map
    -rw-r--r--  1 somebody  staff  513069 Jun  8 18:30 gridjs.production.min.js

**Expected behavior**
Here is what I got from `https://cdn.jsdelivr.net/npm/gridjs@5.0.1/dist/`

    $ ls -l 
    total 640
    -rw-r--r--  1 somebody  staff   60514 Jun  8 18:58 gridjs.js
    -rw-r--r--  1 somebody  staff  201459 Jun  8 19:00 gridjs.js.map
    -rw-r--r--  1 somebody  staff   60729 Jun  8 18:53 gridjs.min.js

**Screenshots**
n.a

**Desktop (please complete the following information):**
n.a.

**Smartphone (please complete the following information):**
n.a.

**Additional context**
n.a.

**Comment by afshinm** [comment]
@i-am-al-x thanks for flagging. I will take a look asap

**Comment by afshinm** [comment]
I just ran a diff locally and both https://unpkg.com/gridjs@5.0.1/dist/gridjs.js and https://cdn.jsdelivr.net/npm/gridjs@5.0.1/dist/gridjs.js are identical. 

I believe in your first curl you wanted to request:

 - https://unpkg.com/gridjs@5.0.1/dist/gridjs.js // <-- correct
 - https://unpkg.com/browse/gridjs@5.0.1/dist/gridjs.js // <-- incorrect

**Comment by i-am-al-x** [comment]
OK, well that explains something.  I can confirm that I took the files from
"browse".
Am I the first person to make this mistake?
Thanks for looking into this.
