### ISSUE TITLE
Get error with find parameters when trying to install v.5

### ISSUE THREAD

**Issue by Eli-Schei** [grid-js/gridjs#623]
**Describe the bug**
I try yo run `npm install gridjs --save` but get the following error

```shell
> gridjs@5.0.1 postinstall C:\Program Files\nodejs\node_modules\gridjs
> find . ! -path '*/node_modules/*' ! -path './package.json' ! -path './tests/dev-server/package.json' -name 'package.json' -execdir npm install \;

FIND: Parameter format not correct
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gridjs@5.0.1 postinstall: `find . ! -path '*/node_modules/*' ! -path './package.json' ! -path './tests/dev-server/package.json' -name 'package.json' -execdir npm install \;`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gridjs@5.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**To Reproduce**
Not sure if it has anything to do with it, but I'm on node v14.15.0

**Expected behavior**
Would expect it to install. 
I ran `npm install gridjs@4.0.0 --save` and it installed that version without problems

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Using windows terminal. Node version 14.15.0. npm version 6.14.8
 - Browser N/A
 - Version [N/A

**Additional context**
I ran `npm install gridjs@4.0.0 --save` and it installed that version without problem. So it looks like a problem with the latest version.

**Comment by afshinm** [comment]
This is because you are using Windows and the `find` syntax is not compatible https://github.com/grid-js/gridjs/blob/master/package.json#L102 -- I will submit a patch asap

**Comment by afshinm** [comment]
@Eli-Schei just published 5.0.2. could you try and install this version please?

**Comment by Eli-Schei** [comment]
It worked now! Thanks for the quick fix :)
![image](https://user-images.githubusercontent.com/60283283/122110247-9c351f80-ce1e-11eb-8e5d-59321bcb95aa.png)

**Comment by wallind** [comment]
```
HackerMan0@DESKTOP-56C5DPL MINGW64 ~/Kyros_Projects/Sidekick/meteor (dependabot/npm_and_yarn/meteor/dev/gridjs-5.0.1)
$ npm install
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\Users\HackerMan0\Kyros_Projects\Sidekick\meteor\node_modules\gridjs
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c find . ! -path '*/node_modules/*' ! -path './package.json' ! -path './tests/dev-server/package.json' -name 'package.json' -execdir npm install \;
npm ERR! find: missing argument to `-execdir'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HackerMan0\AppData\Local\npm-cache\_logs\2021-06-15T23_15_22_247Z-debug.log

HackerMan0@DESKTOP-56C5DPL MINGW64 ~/Kyros_Projects/Sidekick/meteor (dependabot/npm_and_yarn/meteor/dev/gridjs-5.0.1)
```

I had the same problem on Windows 10 at `5.0.1` and `5.0.2` **fixed it for me!**. Thank you so much @afshinm. 😄

**Comment by afshinm** [comment]
@wallind \o/
