### ISSUE TITLE
Use array of objects as datasource 

### ISSUE THREAD

**Issue by mgrivera** [grid-js/gridjs#70]
There is no problem with the actual implementation. Just that I think it is most common to find array of objects as data sources. 

Maybe the solution would be that the grid accepted both ways: array of arrays or array of objects. 

Of course it is  easy to convert from your array of objects to array of arrays; but it would be easy if the grid accepted both ways as posible data sources. 

Many thanks ...

**Comment by afshinm** [comment]
Makes sense. I see how that can be useful.

**Comment by afshinm** [comment]
Currently working on this. will be added to 1.8.0.

**Comment by afshinm** [comment]
@mgrivera Added in 1.8.0: https://gridjs.io/docs/examples/import-json

Thank you!
