### ISSUE TITLE
HTML formatting for json list data

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [grid-js/gridjs#711]
**Is your feature request related to a problem? Please describe.**
Hello, I have some data where a column, 'categories',  includes a list of values, ie. ['animated', 'new', 'featured'] and I would like to be able to apply html to create a link for each individual value within the cell, but it doesn't seem possible. 

When the data supplied to a column is a json list, it will output as a single string, ie. animatednewfeatured
As far as I've figured out, I can use something like 

`formatter: (cell, row) => row.cells[10].data.join(", ")`

That will output it as 'animated, new, featured' but no luck adding html to each value. Would like something like:

`
<a href="animatedurl">animated</a>, <a href="newurl">new</a>, <a href="featuredurl">featured</a>
`

Any thoughts on if this is possible?

**Comment by afshinm** [comment]
Yep, see https://gridjs.io/docs/examples/html-cells

**Comment by fitnycdigitalinitiatives** [comment]
Yes, I saw that, but what I'm having trouble with specifically is when the data in the cell is a array/list. So for the example on that page what if there was more than one email address per person and how would you apply the html for each item in the array?
