### ISSUE TITLE
Feature Request : simple lightweight charts

### ISSUE THREAD

**Issue by happytm** [grid-js/gridjs#74]
**Is your feature request related to a problem? Please describe.**
No it is not related to problem.

**Describe the solution you'd like**
I would like to use this framework on ESP32 microcontroller which will have built in server serving home automation sensor data from json file. It would be nice feature(optional) to create lightweight multi line charts from these data in few selected cells of the row to be displayed with the table in a column like you show image in this example https://gridjs.io/docs/examples/server-side-sort .

**Describe alternatives you've considered**
I have looked into  http://smoothiecharts.org/  & https://pivottable.js.org/examples/montreal_2014.html.
![smoothie](https://user-images.githubusercontent.com/36576353/84714576-15641300-af3c-11ea-9510-479c6901de8b.png)

**Additional context**
Thanks.

**Comment by afshinm** [comment]
Hey @happytm 

This should already be achievable with https://gridjs.io/docs/examples/cell-formatting. We don't really want to provide chart functionality ourselves and as you mentioned, there are some great chart libs that we can use.

I will add an example which will use cell formatting to render charts.

**Comment by happytm** [comment]
It will be nice to have an example.
Thanks.

**Comment by happytm** [comment]
@afshinm  I know you are busy with lot of new features you are adding to this very popular repo but please provide an example of lightweight chart.

Thanks.

**Comment by afshinm** [comment]
hey @happytm, I added a simple example which renders chart element (SVG) in cells: https://gridjs.io/docs/examples/stock-market

**Comment by happytm** [comment]
@afshinm  Thank you so much.
