### ISSUE TITLE
Allow custom styling 

### ISSUE THREAD

**Issue by agoldis** [grid-js/gridjs#75]
Thanks for that great project! 👍🏻

**Is your feature request related to a problem? Please describe.**
I would like to be able to apply custom styles to elements = table, rows, headers etc

**Describe the solution you'd like**
For now just specifying extra classes to be appended to the default would be enough

**Describe alternatives you've considered**
I can override the default style, but that's cumbersome when there's a CSS framework that applies custom complex styling by applying just one class to root element.

**Additional context**
none

**Comment by afshinm** [comment]
Makes sense. I'm working on a ticket to enable custom styling and css-in-js.

**Comment by Karewan** [comment]
Can be also possible to have dual pagination (top and bottom of the grid) in option ?
Thanks

**Comment by afshinm** [comment]
@agoldis custom styling, className and CSS-in-JS is added in 1.7.0.

See https://gridjs.io/docs/examples/css-in-js/ and https://gridjs.io/docs/examples/css-style

thanks!

**Comment by bl4ckck** [comment]
@afshinm how to override the default style? in example I want to override this

```css
.gridjs-search {
    float: left;
}
```
with custom className

```css
.new-class {
    float: right;
}
```
