### ISSUE TITLE
How to avoid the auto height of row while specific set large height table?

### ISSUE THREAD

**Issue by nghiepit** [grid-js/gridjs#756]
**Describe the bug**
How to avoid the auto height of row while specific set large height table?

**To Reproduce**
1. Go to https://gridjs.io/docs/examples/fixed-header
2. Edit height of the table to `2400px`
3. See the problem

**Expected behavior**
The height of the row does not auto scale.

**Screenshots**
![image](https://user-images.githubusercontent.com/4768095/132097128-df64478d-f4af-45c8-bb57-293b4a2749c5.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 5.0.2

**Comment by mike-seekwell** [comment]
@nghiepit did you figure this out?

**Comment by nghiepit** [comment]
@mike-seekwell switch to another library :)

**Comment by damianobarbati** [comment]
@nghiepit which one did you switch to?

**Comment by nghiepit** [comment]
@damianobarbati 
https://www.npmjs.com/package/rc-table and https://github.com/TanStack/table

**Comment by masbaehr** [comment]
I solved the problem like this ... not pretty but working ;) 

```javascript
 //add pseudo rows for equal height
  if(dataforgrid.length < 20){
    for(let i = 0; i < (20-dataforgrid.length); i++){
      dataforgrid.push({});
    }
  }
...
  data: dataforgrid
```
