### ISSUE TITLE
package.json: Incompatible Node version

### ISSUE THREAD

**Issue by South-Paw** [grid-js/gridjs#76]
**Describe the bug**
`gridjs` cannot be installed using Node v13.x

**To Reproduce**
1. Use Node v13
2. Try to install gridjs

**Expected behavior**
You should be able to install it with any version of Node.js

**Screenshots**
![image](https://user-images.githubusercontent.com/2154764/84742553-b4ecd880-b004-11ea-82d6-2754d813bb8c.png)

**Additional context**
Windows 10 and Yarn v1

Your `package.json`'s `engines` key is causing this: 

```
"engines": {
  "node": ">= 12.13 <13"
},
```

**Comment by afshinm** [comment]
@South-Paw fixed in 1.5.1. https://www.npmjs.com/package/gridjs/v/1.5.1

Thanks for reporting it.

**Comment by South-Paw** [comment]
Awesome! Thanks for the quick change 🎉
