### ISSUE TITLE
Question: How to use it in NuxtJS?

### ISSUE THREAD

**Issue by PurpleEyeGH** [grid-js/gridjs#774]
I created a plugin in nuxtjs composed like this

```
import Vue from 'vue'

import * as Grid from 'gridjs-vue';

Vue.use(Grid);
```

In my nuxt.config.js

`  plugins: [
    { src: "~/plugins/gridjs", mode: "client" },
  ],`

But don't work, just the call of import * as Grid from 'gridjs-vue' Suffice it to create an 
`Uncaught ReferenceError: Vue is not defined `

One idea please ?

**Comment by PurpleEyeGH** [comment]
Ok, gridjs-vue is broken https://github.com/grid-js/gridjs-vue/issues/426
It's possible to repair it ?

**Comment by geofany** [comment]
how to use it with nuxt ?

**Comment by mvisonneau** [comment]
FWIW, I managed to get it to work on Nuxt v2.15.8 with the following:

```
~$ yarn add gridjs-vue@v4.0.0
```

```vue
<template>
  <grid :cols="cols" :rows="rows"></grid>
</template>

<script>
  export default {
    components: {
      grid: () => import('gridjs-vue'),
    },
    data() {
      return {
        cols: ['Make', 'Model', 'Year', 'Color'],
        rows: [
          ['Ford', 'Fusion', '2011', 'Silver'],
          ['Chevrolet', 'Cruz', '2018', 'White']
        ]
      }
    }
  }
</script>
```
