### ISSUE TITLE
How to make a No. like datatables? 

### ISSUE THREAD

**Issue by Naravyb** [grid-js/gridjs#78]
how to make columns and their contents without having to retrieve data from serverside like a datatables? if it's in Jquery's datatables, 
I just need to write code

`{
data: 'No',
render: function(data, type, row, meta) {
   return meta.row + 1;
   }
}
`

what if on gridJS?

**Comment by afshinm** [comment]
Not sure if I understand the question but I guess this example can help https://gridjs.io/docs/examples/cell-formatting
