### ISSUE TITLE
log.ts:17 [Grid.js] [ERROR]: ReferenceError: html is not defined

### ISSUE THREAD

**Issue by Naravyb** [grid-js/gridjs#79]
Hello, I use GridJs with a browser, you know <script> ..

I'm currently having problems when I want to use serverside with pagination, I get an undefined html error ... is this really a bug? because the html function is defined in the gridjs.development.js file (https://unpkg.com/gridjs@1.5.1/dist/gridjs.development.js)

The following is the screenshot:
![Untitled](https://user-images.githubusercontent.com/30528814/84799715-33894c00-afec-11ea-937d-d15e46b94478.png)
![Untitled2](https://user-images.githubusercontent.com/30528814/84799722-37b56980-afec-11ea-9185-0957ded040d6.png)

thank you..

**Comment by afshinm** [comment]
@Naravyb how did you import `html`? Can you please create a jsFiddle/Codesandbox for me to debug?

**Comment by Naravyb** [comment]
https://jsfiddle.net/nara014/ex1swno6/2/

like this problem that I found in gridJS, is this really a bug?

**Comment by Naravyb** [comment]
I've found the solution by separating several components from the original grid.development.js file and this works perfectly. Powerful and nice.

https://gist.github.com/Naravyb/27c256f52d8321ec0b6d2d8cf71db179

**Comment by afshinm** [comment]
@Naravyb it's definitely not a bug. `html` function was not imported correctly:

```
    new gridjs.Grid({
        columns: ['Pokemon', 'URL'],
        pagination: {
          limit: 5,
          server: {
            url: (prev, page, limit) => `${prev}?limit=${limit}&offset=${page * limit}`
          }
        },
        server: {
          url: 'https://pokeapi.co/api/v2/pokemon',
          then: data => data.results.map(pokemon => [
            pokemon.name, gridjs.html(`<a href='${pokemon.url}'>Link to ${pokemon.name}</a>`)
          ]),
          total: data => data.count
        } 
      }).render(document.getElementById("wrapper"));
```

https://jsfiddle.net/2041953p/

**Comment by Zonalds** [comment]
Ran into this issue with react. 
Here is how I imported the html; 

`import { Grid, html } from 'gridjs-react';
`

**Comment by joeskeen** [comment]
For anyone trying the JSFiddle above in the future, I was able to get it to work by rewriting it using ES modules: https://jsfiddle.net/6aoqeLtw/
