### ISSUE TITLE
TypeError: Cannot read property 'base' of undefined     

### ISSUE THREAD

**Issue by ignatandrei** [grid-js/gridjs#80]
**Describe the bug**
Grid.js gives an error:
gridjs.production.min.js

 Uncaught (in promise) TypeError: Cannot read property 'base' of undefined
    at e.adjustWidth (gridjs.production.min.js?v=version:15)
    at e.<anonymous> (gridjs.production.min.js?v=version:15)
    at gridjs.production.min.js?v=version:15
    at Object.next (gridjs.production.min.js?v=version:15)
    at s (gridjs.production.min.js?v=version:15)

**To Reproduce**
1. Go to 
https://netcoreblockly.herokuapp.com/blockly.html
2. See console in brower
3. See error

**Expected behavior**
I do not know why happens. Does not affect functionality.

**Desktop (please complete the following information):**
 - Browser Chrome
 

**Additional context**
Source for HTML at https://github.com/ignatandrei/netcoreblockly.

**Comment by afshinm** [comment]
Hey @ignatandrei 

I have seen that error and it happens when your data is empty. Can you take a look and make sure you are passing the correct rows before calling the `render()` function.

**Comment by ignatandrei** [comment]
Should be an error if I pass empty data ? 
After all, it can happen. 
Could you instead verify that the data is empty and return, instead of throwing the error ? ;-)

**Comment by afshinm** [comment]
yeah sure, I will patch the autoWidth method in 1.6.2.

**Comment by afshinm** [comment]
Fixed! thanks for reporting this issue @ignatandrei
