### ISSUE TITLE
RowSelection plugin stops after forceRender() with arg provided to updateConfig()

### ISSUE THREAD

**Issue by Glioburd** [grid-js/gridjs#836]
Hello !

**Describe the bug**
RowSelection doesn't work after a `forceRender()` if an argument is provided to `updateConfig()`.
It will break if you update any property of the object provided to `updateConfig()` such as  `data: {...}`, `search: {...}`, etc.

**To Reproduce**
JsFiddle with a simple table using RowSelection plugin : https://jsfiddle.net/glioburd/v4n1bate/16/
A radio button triggers the table to `forceRender()`, I just provide an object to `updateConfig()` containing `search: false`.
After the forceRender() : `grid.config.plugin.get("myCheckbox").props.store.state.rowIds` is not updated anymore. Front changes (colors) are not changing anymore as well.

**Attempts**
I tried to wark around the problem by setting the `column` array in a const variable, and then binding it to both Grid's constructor and Grid's updateConfig : (https://jsfiddle.net/glioburd/v4n1bate/22/)

```js
const data = [
  // ...
]

const columns = [
  {
    id: "myCheckbox",
    name: "Select",
    plugin: {
      // install the RowSelection plugin
      component: gridjs.plugins.selection.RowSelection,
      // RowSelection config
      props: {
        // use the "email" column as the row identifier
        id: (row) => row.cell(2).data
      }
    }
  } // ...
]

const grid = new gridjs.Grid({
  search: true,
  columns: columns,
  data: data
}).render(document.getElementById("wrapper"))

grid.updateConfig({
  search: false,
  columns: columns
}).forceRender()
```
Same problem.

**Comment by MattiasFestin** [comment]
I have the same problem.

I use grid-js from the Svelete component wrapper (`gridjs-svelte`). And when doing dynamic updates the forceRender bug makes row selection unresponsive.

This bug makes Svelte version of grid-js unusable for me.
