### ISSUE TITLE
Grid re-renders or resets internal state when updating other elements

### ISSUE THREAD

**Issue by rbakker-tournamentsoftware** [grid-js/gridjs#840]
**Describe the bug**
It seems that when changing other state variables in React, the grid is re-rendering/reloading. So when you have options like sort, resize, search enabled, these properties are reset. Or is this related to #227 ?

**To Reproduce**
For example see https://codesandbox.io/s/gridjs-react-forked-1jo43?file=/src/App.js
1. Resize a column, and/or change column sorting.
2. Click the button

Another example using https://gridjs.io/docs/integrations/react (however this is more to be expected because the table data changes);
1. Add options `sort={{ multiColumn: false }} resizable={true}` to the grid in the Live editor
2. Resize a column, and/or change column sorting.
3. Click the "Add record" button

**Expected behavior**
It would be nice if the grid doesn't re-render when there is no change in the data (example 1) - or if the state of display properties could be kept in memory?

Thanks for the amazing work on gridjs! 👍

**Comment by Packoverflow** [comment]
^
Thanks for the amazing work on gridjs! +1

**Comment by hackslashX** [comment]
> Seconding. Would like to .forceRender() but keep current page/sorting/filter etc. $50.

@Packoverflow 
I know this is an old comment, but I found a workaround so adding it here. If your configuration is unchanged, you can do the following in React to achieve a data reload and re-render the table without affecting pagination, sorting, etc.

1.  Create a reference.
`const gridRef = React.useRef(null)`
2. Add this reference to Grid instance.
`...
ref={gridRef}
pagination={...}
...`
3. On button press or any other action do the following:
`
const current = gridRef.current.instance.config
current.pipeline.clearCache()
current.pipeline.process().then((data) => {
    current.tableRef.current.props.data = data
    current.tableRef.current.forceUpdate()
})
`
4. Optionally, you can also append a class name to `current.container.classList` for any loading animation you might want to show while the data is loading.

**Comment by tap2k** [comment]
This solution isnt working for me when I update the page state with useState()
