### ISSUE TITLE
Horizontal scroll bar appears when fixed header option is used

### ISSUE THREAD

**Issue by smashmirrorcardboardface** [grid-js/gridjs#843]
Horizontal scroll bar appears when fixed header option is used and vertical scroll bar is displayed

**To Reproduce**
add fixed header option to a table with more rows than there is space available to display all rows on screen
vertical scroll bar is shown.
horizontal scrollbar is shown.

**Expected behavior**
table should re-adjust width to take into account the vertical scroll bar

**Comment by 1fc0nfig** [comment]
bb
