### ISSUE TITLE
Table contents do not resize when browser window is resized (to a larger size)

### ISSUE THREAD

**Issue by Reve** [grid-js/gridjs#867]
**Describe the bug**
On window resize to a larger width than initial, the table contents are not resized to fit the new width.

**To Reproduce**
1. Resize the window to a bigger size
2. See error

**Expected behavior**
The columns should resize automaticaly to fit the new width.

**Screenshots**
***Initial***
![Screenshot 2021-11-25 at 13 00 59](https://user-images.githubusercontent.com/735340/143429701-4d85df86-8677-4006-8374-ddba49fe5fb8.png)
***REs***
![Screenshot 2021-11-25 at 13 01 05](https://user-images.githubusercontent.com/735340/143429717-7132ef45-4b6f-49d3-8ce4-17dd2fe9eded.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome, firefox

**Additional context**
The code used to init the Grid
`<Grid data={members} columns={['Name', 'Email']} />`

**Comment by Reve** [comment]
A quick fix I found is to add width: 100% to table.gridjs-table and change the table-layout from fixed to auto. I don't know what other implications these changes might have to other functionalities.

**Comment by ubergeoff** [comment]
Yes, please can we fix the css to:

```
table.gridjs-table {
  width: 100%;
  border-collapse: collapse;
  text-align: left;
  display: table;
  margin: 0;
  padding: 0;
  overflow: auto;
  table-layout: auto; }
```

??

**Comment by ubergeoff** [comment]
Would the above be possible..?

**Comment by rafzei** [comment]
It's not needed to hardode in the code. Here is example:
```js
        style: {
            table: {
                'width': '100%'
            }
        }
```
The thing is, that if you put `width: 100%` the mobile view won't be vertically scrollable anymore.

**Comment by PumpkinPeasant** [comment]
Adding width helps with the empty space but it does not fix the problem with resize to other direction. When you make window smaller than initial size, table stays off the boundaries
