### ISSUE TITLE
Receive `cell.data` on plugin

### ISSUE THREAD

**Issue by iamyuu** [grid-js/gridjs#904]
**Describe the bug**
When using `plugin` as cell, the `cell.data` receive `null`

**Expected behavior**
When using `plugin`, the props should receive similar value with formatter cell

**To Reproduce**
1. Check the [codesandbox](https://codesandbox.io/s/gridjs-render-plugin-repro-t2lk0?file=/src/index.js)
2. Open the console
3. See `this.props.cell.data` is null

**Screenshots**
![props log](https://user-images.githubusercontent.com/45778229/149643944-65f4709c-7e94-49ea-8cfb-49041d11a769.png)

**Additional context**
`gridjs-svelte` use plugin for rendering Svelte component in the cell

**Comment by carlos-dubon** [comment]
any workaround for this?

**Comment by GaretJax** [comment]
It looks like there is a bug where an additional `null` value is inserted at the position of the column with a plugin. If there are additional columns after the one with a plugin, their values are all offset by one position.

If you look at https://svelte.dev/repl/0c77bee765c1458d825a4df13aefb5a4?version=3.46.6, you will see that the plugin accesses the cell at index 3, even if it should access the one at index 2 (which is indeed `null`).

**Comment by GaretJax** [comment]
It seems that the code does not expect the data to contain a value at all for the column with a plugin. A possible workaround is to add an additional column with `hidden: true` with the data and use that in the plugin by getting the data via `row.cell(hiddenColumnIndex).data`.

**Comment by GaretJax** [comment]
+1

**Comment by DVDAndroid** [comment]
+1

**Comment by luandnh** [comment]
Hi there, I think problem comes from you not set data prop in column. 
I just add `data: (row) => row` and in component return email from data `{cell.data.email}`

![image](https://user-images.githubusercontent.com/49023411/200179356-4121a7db-be9d-486c-9728-ab1a9d26c985.png)
![image](https://user-images.githubusercontent.com/49023411/200179382-01ea7910-a69c-4f8a-a441-379aa7a32a5c.png)
