### ISSUE TITLE
 Is there a way to code control the checkboxes created in grid.js?

### ISSUE THREAD

**Issue by kimkanghyune** [grid-js/gridjs#945]
Rather than directly controlling the user, I want to control it by writing code.
The documentation example of the Selection Plugin related to this also seems to lack explanation.
And it would be nice to add a function to limit the number of checkboxes that can be selected.

**Comment by kaanrkaan** [comment]
I was also searching into this topic, after digging deeper into the codebase I found the solution

If you are trying to access within a plugin:
`this.config.dispatcher.dispatch()`
