### ISSUE TITLE
Allow Pagination to be on top as well

### ISSUE THREAD

**Issue by StephanMa** [grid-js/gridjs#951]
**Is your feature request related to a problem? Please describe.**
We are evaluating gridjs for one of our projects. Sometimes you can have 100 records per page. So its really annoying to scroll to the bottom of the page for pagination.

**Describe the solution you'd like**
It would like to enable pagination to be on top **and** bottom of the table.

**Describe alternatives you've considered**
n/a

**Additional context**
Would be fine to tune mermaid.css for our self if its necesarry.

**Comment by j-greig** [comment]
Would love this feature also. Even a hack to add it in would be great. Thank you
