### ISSUE TITLE
Only render visible rows (virtual list)

### ISSUE THREAD

**Issue by mhkeller** [grid-js/gridjs#952]
**Is your feature request related to a problem? Please describe.**
It would be nice if this library only rendered rows that were visible on the screen – a so-called virtual list. Other table libraries (such as [Tabulator](tabulator.info/)) already do this. It helps avoid the page being bogged down with a lot of unseeable data.

**Comment by damianobarbati** [comment]
Indeed virtualization would be a great future! 
It's also a great alternative to pagination when dataset is small (<5MB), allowing less backend configuration (single HTTP call) and a smooth UX experience 🙂

**Comment by mhkeller** [comment]
I think this issue is still a good idea
