### ISSUE TITLE
Initial Sort Column

### ISSUE THREAD

**Issue by cdarissian** [grid-js/gridjs#954]
Functionality to allow you to set the initial sort column on first load, so that it's correct represented by the column arrows

**Comment by RafeSafari** [comment]
It would be nice to consider this issue as a feature request.
As an alternate solution, some APIs would work as well.
`grid.sort('id')` for instance!

**Comment by bruno-buiret** [comment]
I am also interested in this :)

**Comment by mmays77** [comment]
I don't know how this issue could be getting kicked down the road and marked as stale. Displaying historic data in a transaction system is often needing the most recent rows first. A descending sort on a column such as a date on initial load is a glaring deficiency.
