### ISSUE TITLE
Ability to have server side sort AND server side pagination

### ISSUE THREAD

**Issue by techgems** [grid-js/gridjs#959]
**Is your feature request related to a problem? Please describe.**
It's a feature request after following the documentation and being unable to join both server side sort and server side pagination. They both do network calls and the "prev" parameter does not contain information that may have come from the other function setting up query string values for the server side.

**Describe the solution you'd like**
A way to be able to use server side sort and pagination at the same time.

**Additional context**
Really that's all there is, I can add a code demo of what I am attempting and how it doesn't work if needed.

**Comment by azmeuk** [comment]
Thank you stale bot, but I am still interested in this issue. :pray:

**Comment by Aloysb** [comment]
@azmeuk I can take a look at this.

Can you share a code demo to speed up the process? 👍 

Cheers.

Cheers
