### ISSUE TITLE
Selection plugin: *select all* checkbox in the table header

### ISSUE THREAD

**Issue by azmeuk** [grid-js/gridjs#967]
I would love a main checkbox to select/unselect several rows at a time.

When the selection plugin is used, a *(de)select all* checkbox in the header would be awesome. If checked it would check all the checkboxes (and select all the rows), if unchecked it would unselect all the rows. If some rows are selected and other are not, the checkbox would appear [undeterminate](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox#indeterminate_state_checkboxes).

I am not sure if this checkbox would need to check only the items on the current page, or all the items available. I suppose both case can be useful, maybe this can be made an option?

What do you think?

**Comment by azmeuk** [comment]
Please stale bot, let this issue opened.

**Comment by azmeuk** [comment]
@stale bot, please leave this ticket alon :)

**Comment by aaronsmulktis** [comment]
I am glad to have found this thread! Because I, too, am hunting down a way to make this feature possible!

Thanks for the great package :)

**Comment by VenatusSimpleX** [comment]
Any updates? It seems like it's stuck on stale, I need this feature as well :')

**Comment by freehex** [comment]
hi guys, try this:
```js
<body>
  <div id="wrapper"></div>

  <script>
    function toggle(cb){
      if(cb.checked == true) {
          grid.config.columns[0].data = true;
          grid.forceRender();
          document.getElementById("allCheckbox").checked = true;
      } else {
          grid.config.columns[0].data = false
          grid.forceRender();
      }
    }
    
    const dataRows = [{
      isChecked: false,
      productName: "Some product 1",
      count: 15,
    },{
      isChecked: true,
      productName: "Some product 2",
      count: 20,
    },{
      isChecked: false,
      productName: "Some product 3",
      count: 6,
    }];
    
    const grid = new gridjs.Grid({
      columns: [
          {
            id: 'selectRow',
            name: gridjs.html('<input id="allCheckbox" type="checkbox" onclick="toggle(this);"/>'),
            data: (row) => row.isChecked, 
            plugin: {
              component: gridjs.plugins.selection.RowSelection
            }
          },
          { 
            name: 'Product',
            data: (row) => row.productName
          },
          { 
            name: 'Count',
            data: (row) => row.count
          }
      ],
      data: dataRows,
      style: {
        th: {
          'text-align': 'center'
        }
      }
    });

    grid.render(document.getElementById("wrapper"));
  </script>
</body>
```

**Comment by Marin-Matosevic** [comment]
I have been searching for this feature as it would be highly beneficial. I have devised a quick but effective solution using jQuery. Within the "selectRow" column I have included a checkbox and added an event listener to handle changes.

inside new Grid({});

`		columns: [            
			{
				id: 'selectRow',
				name: html( '<input type="checkbox" name="custom_toggle" />' ),
				plugin: {
					component: RowSelection,
				},
				width: '60px;',
			}
            { /* other column */ }
            { /* other column */ }
            { /* other column */ }
        ];`

And jQuery
`	$( document ).on( 'change', '[name="pph_toggle"]', function ( e ) {
		if ( $( this ).is( ':checked' ) ) {
			$( '.gridjs-tr' )
				.not( '.gridjs-tr-selected' )
				.find( '.gridjs-checkbox' )
				.click();
		} else {
			$( '.gridjs-tr-selected' ).find( '.gridjs-checkbox' ).click();
		}
	} );`

**Comment by Marin-Matosevic** [comment]
I have been searching for this feature as it would be highly beneficial. I have devised a quick but effective solution using jQuery. Within the "selectRow" column I have included a checkbox and added an event listener to handle changes.

inside new Grid({});

```JS
columns: [            
    {
        id: 'selectRow',
        name: html( '<input type="checkbox" name="custom_toggle" />' ),
            plugin: {
                component: RowSelection,
           },
        width: '60px;',
   }
    { /* other column */ }
    { /* other column */ }
    { /* other column */ }
];
```

And jQuery
```JS
$( document ).on( 'change', '[name="pph_toggle"]', function ( e ) {
    if ( $( this ).is( ':checked' ) ) {
        $( '.gridjs-tr' ).not( '.gridjs-tr-selected' ).find( '.gridjs-checkbox' ).click();
    } else {
        $( '.gridjs-tr-selected' ).find( '.gridjs-checkbox' ).click();
    }
} );```
