### ISSUE TITLE
when using react, styling by default isn't working.

### ISSUE THREAD

**Issue by enahs** [grid-js/gridjs#97]
**Describe the bug**
I rolled my own react app from scratch. I'm using parcel for bundling et al.
after installing grid JS, the result looks un-styled.

I'd expect that it would be styled. poked around in the `dist` folder and importing this seemed to correct it.

```js
import "gridjs/dist/theme/mermaid.min.css";
```

probably just need to update the docs for react or add an easier way to grab this asset (maybe some lib folder?)

**To Reproduce**
1. `yarn add gridjs gridjs-react`
2. `import { Grid } from 'gridjs-react';`
3. make some simple grid, copy paste from the example, say.
4. notice grid unstyled. 

**Expected behavior**
Grid should be styled as per the examples in the documentation

**Screenshots**
<img width="684" alt="Screen Shot 2020-06-22 at 3 49 22 PM" src="https://user-images.githubusercontent.com/1907761/85342654-fe737280-b49f-11ea-8bd7-3279636e0a40.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Smartphone (please complete the following information):**
 - Version 83

**Additional context**

**Comment by afshinm** [comment]
@enahs thanks Shane. Yes, we should update the docs to reflect that.

**Comment by afshinm** [comment]
Looks like that is actually mentioned in this page https://gridjs.io/docs/install -- were you able to find that page easily?

**Comment by enahs** [comment]
Ah, i am clearly guilty of not reading the manual thoroughly. Sorry about
that. I installed with yarn, so i skipped the npm stuff.
elsewhere in the [docs](https://gridjs.io/docs/integrations/react#usage) it
is not a priori obvious.

**Comment by afshinm** [comment]
sure, thanks @enahs!
