### ISSUE TITLE
InsertRow

### ISSUE THREAD

**Issue by creativeprogramming** [grid-js/gridjs#970]
It would be useful to have a method to dyniamically add rows to an existing grid, e.g. I've an application with socket.io that automatically have to add rows to an existing table

**Comment by ewwink** [comment]
you can do

```javascript
myGrid.config.data.push(['a', 'b']);
myGrid.forceRender();
```

**Comment by iilyak** [comment]
I have a similar question. however in my cases I am having a problem with pagination.
Let's say user currently viewing page 3. Then I do a `data.push` followed by `forceRender`. Immediately the current page becomes 1. 

I try to use gridjs to display log events. Therefore I add entries every time I got new event from backend.
