### ISSUE TITLE
Dynamic styling for tr Row doesn't work

### ISSUE THREAD

**Issue by s-keerthi-code** [grid-js/gridjs#974]
**Describe the bug**
I have  a situation where I have to add styles to a row based on the row data. However only static styling for tr is possible. How can I do this?

**Comment by ewwink** [comment]
I need this too, but temporary solution use `grid.on(ready)` function

```javascript
myGrid.on('ready', () => {
      $('#myTable td:nth-child(1)').each((index, td) => {
          if (td.textContent > 0)
              td.parentElement.className = "myRowClass";
      })
})
```

**Comment by BafS** [comment]
Same question, we can customize the cell easily, we can get the column id, but what about the complete row (aka tr)?
