### ISSUE TITLE
re-render the grid after a particular event like clcking a button

### ISSUE THREAD

**Issue by abhaysinghs772** [grid-js/gridjs#978]
**Is your feature request related to a problem? Please describe.**
I am using grid.js in my admin panel of a project, where i have a button in my action's column.
i want to refresh the grid after the click event of button.
i don't want to reload the entire page again to show updated data.

i am using vanilla javaScript only.

**Additional context**
![Screenshot from 2022-05-17 10-59-41](https://user-images.githubusercontent.com/67998122/168736054-5f3e537d-88dd-43c0-9fc7-64bd093fbca8.png)

**Comment by bokunodev** [comment]
you could listen on `cellClick` event. the callback definition is in here
https://github.com/grid-js/gridjs/blob/5fae726edb4471f517115bc377507e7b56453be4/src/view/table/events.ts#L6

**Comment by vicentematus** [comment]
Hey @abhaysinghs772 how did you add custom icons  /buttons inside Grid.js?

**Comment by vicentematus** [comment]
> @vicentematus you can put html inside the cell.
> [its on the documentation.](https://gridjs.io/docs/examples/html-header-cells/)

Thank you very much. Now it's working

**Comment by naaando** [comment]
I need that too, very confused on how to update after some data change, I'll attempt to forceRender but I'm unsure that is what I need

**Comment by LB26121** [comment]
I have the same issue: on button click in a cell the table re-renders.
