### ISSUE TITLE
Columns has no effect when using from: htmlTable as a datasource

### ISSUE THREAD

**Issue by mgrecol** [grid-js/gridjs#992]
When we using from: HTMLTABLE
the grid.js seems to ignore anything that is in the "columns" declaration.
the below example, the first column ID should be hidden and the 2nd column should have an <a>  link. The rendered table does not not have these.

Example:
 var tbl = document.getElementById('TestRef');
 var dest =  document.getElementById('TableDest');
var   grid = new gridjs.Grid({
					columns : [{
						name: 'id',
						hidden: true
					},
						{
						name: 'Name',
						formatter: (cell,row,column)=>{ return gridjs.html( '<a href = "https://google.com/'+row.cells[0].data+'">'+ row.cells[1].data+'</a>')}
					},
					{name: "Email"
						
					},
					{name: "Value"}
					],
        	       from: tbl,
        	      fixedHeader: true,
        	      height: '200px',
        	      width: '700px',
        	    
        	      sort: true,
        	       search: true
        	    }).render(dest);

<table id="TestRef">
        <thead>
          <tr>
            <th>id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
          <tr>
		  <td>1</td>
            <td>John</td>
            <td>john@example.com</td>
            <td>100</td>
          </tr>
		  <tr>
		  <td>2</td>
            <td>Mike</td>
            <td>mike@example.com</td>
            <td>13</td>
          </tr>
		  <tr>
		  <td>3</td>
            <td>Oxford</td>
            <td>oxford@example.com</td>
            <td>15</td>
          </tr>
	</tbody>
</table>

**Comment by oferze** [comment]
This is a real bug (although closed by the bot), unless the correct usage is undocumented. Can someone please look at this?

**Comment by brandonrobertz** [comment]
Yes this is still broken, making numeric sort impossible by default when using a table as a source.
