### ISSUE TITLE
UI for number of Rows displayed

### ISSUE THREAD

**Issue by He2car** [grid-js/gridjs#997]
**Is your feature request related to a problem? Please describe.**
As a user I want to have a UI element to select how many rows are displayed in the table so I can see more/less rows at once and reduce/increase the number of pages at the same time.

**Describe the solution you'd like**
A dropdown box next to the pages with a few option such as (5, 10, 25, 50, 100). The selected option will then modify the value of `limit:  ` in the pagination plugin.

<img width="225" alt="Screenshot 2022-06-14 at 9 55 14 AM" src="https://user-images.githubusercontent.com/105329131/173476871-0aea360a-9f20-487c-a5fb-3fba493637bb.png">

**Additional context**
At UI level this could look something like the example below
<img width="206" alt="Screenshot 2022-06-14 at 9 52 42 AM" src="https://user-images.githubusercontent.com/105329131/173476711-ef3bb60b-1961-4d92-afb2-72d95dbe5796.png">
<img width="201" alt="Screenshot 2022-06-14 at 9 52 50 AM" src="https://user-images.githubusercontent.com/105329131/173476722-270bfda4-f7e9-4b31-ac67-5323419bd0b4.png">

**Comment by noehmeier** [comment]
I am also looking for this feature. The stale-bot closed this automatically, but what does a contributor thinking about this feature?
